import {
  Pedido,
  ProductItem,
  AutomationRule,
  RecurrenceConfig,
  ShiftInfo,
  Incidencia,
  ResumenKPIs,
  StockIngredientItem,
  StockMovement,
  Conversation,
} from "./types";

export const INITIAL_PRODUCTS: ProductItem[] = [
  {
    id: "prod-01",
    code: "EMP-01",
    name: "Empanada de Carne Cortada a Cuchillo",
    category: "Empanadas",
    price: 5500,
    imageUrl: "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 45,
    prepTimeMinutes: 12,
    description: "Carne tierna seleccionada, cebolla de verdeo, huevo duro y especias autóctonas en masa hojaldrada.",
    demandTag: "Alta demanda",
    activeOrdersCount: 4,
    salesCount: 482,
    popularityRank: 1,
    rating: 4.9,
    reviewsCount: 146,
    modifiers: [
      {
        id: "mod-coccion-1",
        title: "Tipo de Cocción",
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: "opt-c-1", name: "Al Horno de Piedra (Recomendado)", priceDelta: 0, isDefault: true },
          { id: "opt-c-2", name: "Frita en Grasa Criolla", priceDelta: 500 },
        ],
      },
      {
        id: "mod-salsa-1",
        title: "Salsa Extra Opcional",
        minSelect: 0,
        maxSelect: 2,
        options: [
          { id: "opt-s-1", name: "Chimichurri Casero 60ml", priceDelta: 1500 },
          { id: "opt-s-2", name: "Salsa Criolla Picante 60ml", priceDelta: 1500 },
        ],
      },
    ],
    reviews: [
      {
        id: "rev-1",
        author: "Santiago Morales",
        rating: 5,
        date: "Hace 2 días",
        comment: "La mejor empanada de carne de la zona. Jugosa, masa crujiente y sin exceso de grasa.",
        verifiedOrder: true,
      },
      {
        id: "rev-2",
        author: "Valeria Gómez",
        rating: 5,
        date: "Hace 4 días",
        comment: "El corte a cuchillo se nota muchísimo en la textura. Llegaron bien calientes al trabajo.",
        verifiedOrder: true,
      },
      {
        id: "rev-3",
        author: "Martín P.",
        rating: 4,
        date: "Hace 1 semana",
        comment: "Excelente sabor, muy bien condimentada. 100% recomendada.",
        verifiedOrder: true,
      },
    ],
  },
  {
    id: "prod-02",
    code: "EMP-02",
    name: "Empanada de Pollo al Verdeo",
    category: "Empanadas",
    price: 5500,
    imageUrl: "https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 32,
    prepTimeMinutes: 12,
    description: "Pechuga desmenuzada, morrón rojo salteado y salsa cremosa de verdeo.",
    demandTag: "Alta demanda",
    activeOrdersCount: 3,
    salesCount: 365,
    popularityRank: 2,
    rating: 4.8,
    reviewsCount: 98,
    modifiers: [
      {
        id: "mod-coccion-2",
        title: "Tipo de Cocción",
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: "opt-c-3", name: "Al Horno de Piedra", priceDelta: 0, isDefault: true },
          { id: "opt-c-4", name: "Frita", priceDelta: 500 },
        ],
      },
    ],
    reviews: [
      {
        id: "rev-4",
        author: "Camila R.",
        rating: 5,
        date: "Hace 3 días",
        comment: "Súper cremosa y el pollo muy tierno. Es mi favorita para pedir en la oficina.",
        verifiedOrder: true,
      },
      {
        id: "rev-5",
        author: "Nicolás B.",
        rating: 5,
        date: "Hace 6 días",
        comment: "La combinación de verdeo y pollo es perfecta. Excelente cocción en horno.",
        verifiedOrder: true,
      },
    ],
  },
  {
    id: "prod-03",
    code: "EMP-03",
    name: "Empanada de Jamón y Queso Mozzarella",
    category: "Empanadas",
    price: 5200,
    imageUrl: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 28,
    prepTimeMinutes: 10,
    description: "Jamón cocido de primera calidad y abundante queso mozzarella fundido.",
    activeOrdersCount: 2,
    salesCount: 290,
    popularityRank: 4,
    rating: 4.7,
    reviewsCount: 84,
    reviews: [
      {
        id: "rev-6",
        author: "Esteban D.",
        rating: 5,
        date: "Hace 5 días",
        comment: "Queso de verdad que estira y buen jamón. Los chicos las adoran.",
        verifiedOrder: true,
      },
    ],
  },
  {
    id: "prod-04",
    code: "EMP-04",
    name: "Empanada de Humita Cremosa",
    category: "Empanadas",
    price: 4800,
    imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: false,
    stockEstimated: 0,
    prepTimeMinutes: 10,
    description: "Choclo dulce en grano y crema suave con toque de nuez moscada y queso criollo.",
    demandTag: "Sugerencia de promo",
    activeOrdersCount: 0,
    salesCount: 180,
    popularityRank: 6,
    rating: 4.6,
    reviewsCount: 52,
    reviews: [
      {
        id: "rev-7",
        author: "Lucía Fernández",
        rating: 5,
        date: "Hace 1 semana",
        comment: "Relleno dulce en su punto exacto. Lástima que se agota rápido.",
        verifiedOrder: true,
      },
    ],
  },
  {
    id: "prod-05",
    code: "CMB-01",
    name: "Combo Docena Mixta Clásica",
    category: "Combos",
    price: 54000,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 20,
    prepTimeMinutes: 20,
    description: "12 empanadas a elección del maestro pastelero + 2 salsas caseras + 2 bebidas 500ml.",
    demandTag: "Alta demanda",
    activeOrdersCount: 5,
    salesCount: 340,
    popularityRank: 3,
    rating: 4.9,
    reviewsCount: 112,
    modifiers: [
      {
        id: "mod-beb-combo",
        title: "Elige las 2 Bebidas Incluidas",
        minSelect: 2,
        maxSelect: 2,
        options: [
          { id: "opt-b-1", name: "Gaseosa Cola 354ml", priceDelta: 0, isDefault: true },
          { id: "opt-b-2", name: "Limonada Natural", priceDelta: 1000 },
          { id: "opt-b-3", name: "Agua Mineral 500ml", priceDelta: 0 },
        ],
      },
    ],
    reviews: [
      {
        id: "rev-8",
        author: "Grupo Tech Solutions",
        rating: 5,
        date: "Ayer",
        comment: "Pedimos 3 combos para el almuerzo del equipo. Llegó todo impecable y a tiempo.",
        verifiedOrder: true,
      },
    ],
  },
  {
    id: "prod-06",
    code: "CMB-02",
    name: "Combo Ejecutivo Express",
    category: "Combos",
    price: 18500,
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 30,
    prepTimeMinutes: 10,
    description: "3 empanadas a elección + 1 gaseosa o agua mineral + 1 alfajor artesanal de postre.",
    activeOrdersCount: 2,
    salesCount: 245,
    popularityRank: 5,
    rating: 4.8,
    reviewsCount: 76,
    reviews: [
      {
        id: "rev-9",
        author: "Franco Martínez",
        rating: 5,
        date: "Hace 2 días",
        comment: "La relación precio-calidad es insuperable para el almuerzo diario.",
        verifiedOrder: true,
      },
    ],
  },
  {
    id: "prod-07",
    code: "ACOM-01",
    name: "Papas Rústicas al Romero",
    category: "Acompañamientos",
    price: 8500,
    imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 25,
    prepTimeMinutes: 15,
    description: "Papas cortadas a mano con piel, horneadas con aceite de oliva, sal marina y romero fresco.",
    demandTag: "Alta demanda",
    activeOrdersCount: 3,
    salesCount: 195,
    popularityRank: 7,
    rating: 4.9,
    reviewsCount: 42,
    modifiers: [
      {
        id: "mod-tam-papas",
        title: "Elige tu Tamaño de Porción",
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: "opt-p-reg", name: "Porción Individual (250g)", priceDelta: 0, isDefault: true },
          { id: "opt-p-gra", name: "Porción Familiar para Compartir (500g)", priceDelta: 5500 },
        ],
      },
    ],
    reviews: [],
  },
  {
    id: "prod-08",
    code: "ACOM-02",
    name: "Salsa Chimichurri Casera 120ml",
    category: "Acompañamientos",
    price: 3000,
    imageUrl: "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 50,
    prepTimeMinutes: 1,
    description: "Receta tradicional con perejil fresco, orégano, ajo y ají molido macerado.",
    activeOrdersCount: 4,
    salesCount: 310,
    popularityRank: 8,
    rating: 4.9,
    reviewsCount: 35,
    reviews: [],
  },
  {
    id: "prod-09",
    code: "BEB-01",
    name: "Gaseosa Cola 354ml",
    category: "Bebidas",
    price: 4500,
    imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 60,
    prepTimeMinutes: 2,
    description: "Lata fría lista para despacho inmediato.",
    activeOrdersCount: 6,
    salesCount: 510,
    popularityRank: 9,
    rating: 4.9,
    reviewsCount: 65,
    reviews: [],
  },
  {
    id: "prod-10",
    code: "BEB-02",
    name: "Limonada Natural con Menta y Jengibre 500ml",
    category: "Bebidas",
    price: 6500,
    imageUrl: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 35,
    prepTimeMinutes: 3,
    description: "Exprimida en el momento con limones frescos, menta y hielo frappé.",
    activeOrdersCount: 4,
    salesCount: 220,
    popularityRank: 10,
    rating: 4.8,
    reviewsCount: 48,
    reviews: [],
  },
  {
    id: "prod-11",
    code: "POS-01",
    name: "Alfajor de Maicena Artesanal con Dulce de Leche",
    category: "Postres",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 40,
    prepTimeMinutes: 1,
    description: "Tapas suaves que se deshacen en la boca, abundante dulce de leche repostero y coco rallado.",
    activeOrdersCount: 3,
    salesCount: 280,
    popularityRank: 11,
    rating: 5.0,
    reviewsCount: 55,
    reviews: [],
  },
];

export const INITIAL_ORDERS: Pedido[] = [
  {
    id: "PED-1024",
    customerName: "Mariana Silva",
    customerPhone: "+54 11 9482-1102",
    customerAddress: "Av. Santa Fe 3421, 4to B",
    channel: "whatsapp",
    type: "inmediato",
    status: "NUEVO",
    items: [
      { productId: "prod-01", name: "Empanada de Carne Cortada a Cuchillo", quantity: 6, unitPrice: 5500, option: "Horneada" },
      { productId: "prod-02", name: "Empanada de Pollo al Verdeo", quantity: 6, unitPrice: 5500, option: "Horneada" },
      { productId: "prod-07", name: "Gaseosa Cola 354ml", quantity: 2, unitPrice: 4500 },
    ],
    total: 75000,
    createdAt: "18:28",
    estimatedMinutes: 20,
    elapsedMinutes: 2,
    urgency: "A_TIEMPO",
    isAIOrigin: true,
    aiRawMessage: "Hola! Queremos media docena de carne a cuchillo y media de pollo al verdeo, ambas al horno, y dos cocas frías porfa.",
    aiConfidence: "Alta",
    notes: "Tocar timbre 4B directamente.",
    history: [
      {
        timestamp: "18:28",
        toStatus: "NUEVO",
        user: "Necto IA Gateway",
        note: "Interpretado con confianza Alta desde WhatsApp. Requiere confirmación manual.",
      },
    ],
  },
  {
    id: "PED-1025",
    customerName: "Dr. Roberto Méndez",
    customerPhone: "+54 11 5521-8890",
    channel: "presencial",
    type: "inmediato",
    status: "NUEVO",
    items: [
      { productId: "prod-06", name: "Combo Ejecutivo Express", quantity: 1, unitPrice: 18500, notes: "Carne suave + Pollo + Jamón/Queso" },
    ],
    total: 18500,
    createdAt: "18:31",
    estimatedMinutes: 10,
    elapsedMinutes: 1,
    urgency: "A_TIEMPO",
    notes: "Para consumir en mostrador / llevar.",
    history: [
      {
        timestamp: "18:31",
        toStatus: "NUEVO",
        user: "Cajero 1 (Lucas Gómez)",
        note: "Ingresado por mostrador directo.",
      },
    ],
  },
  {
    id: "PED-1022",
    customerName: "Ignacio Ferreyra",
    customerPhone: "+54 11 3341-9988",
    customerAddress: "Billinghurst 1840",
    channel: "web",
    type: "inmediato",
    status: "CONFIRMADO",
    items: [
      { productId: "prod-05", name: "Combo Docena Mixta Clásica", quantity: 1, unitPrice: 54000 },
    ],
    total: 54000,
    createdAt: "18:20",
    estimatedMinutes: 25,
    elapsedMinutes: 12,
    urgency: "A_TIEMPO",
    turnNumber: 14,
    history: [
      { timestamp: "18:20", toStatus: "NUEVO", user: "Portal Web Necto" },
      { timestamp: "18:21", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Sistema", ruleName: "Regla Conf. Automática #1" },
    ],
  },
  {
    id: "PED-1020",
    customerName: "Tech Solutions S.A. (Reunión)",
    customerPhone: "+54 11 4455-6677",
    customerAddress: "Av. Corrientes 1250, Piso 8",
    channel: "whatsapp",
    type: "programado",
    status: "EN_PREPARACION",
    items: [
      { productId: "prod-05", name: "Combo Docena Mixta Clásica", quantity: 3, unitPrice: 54000 },
      { productId: "prod-07", name: "Gaseosa Cola 354ml", quantity: 6, unitPrice: 4500 },
    ],
    total: 189000,
    createdAt: "17:45",
    scheduledTime: "18:45",
    estimatedMinutes: 40,
    elapsedMinutes: 46,
    urgency: "RETRASADO",
    turnNumber: 9,
    notes: "Empaquetar por separado en cajas térmicas.",
    history: [
      { timestamp: "17:45", toStatus: "NUEVO", user: "Operador (Martín Ruiz)" },
      { timestamp: "17:50", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Martín Ruiz" },
      { timestamp: "18:05", fromStatus: "CONFIRMADO", toStatus: "EN_PREPARACION", user: "Cocina (Chef Carlos)" },
    ],
  },
  {
    id: "PED-1021",
    customerName: "Camila Benítez",
    customerPhone: "+54 11 6789-1234",
    channel: "whatsapp",
    type: "inmediato",
    status: "EN_PREPARACION",
    items: [
      { productId: "prod-01", name: "Empanada de Carne Cortada a Cuchillo", quantity: 4, unitPrice: 5500 },
      { productId: "prod-03", name: "Empanada de Jamón y Queso Mozzarella", quantity: 4, unitPrice: 5200 },
    ],
    total: 42800,
    createdAt: "18:15",
    estimatedMinutes: 20,
    elapsedMinutes: 17,
    urgency: "PROXIMO",
    turnNumber: 11,
    history: [
      { timestamp: "18:15", toStatus: "NUEVO", user: "WhatsApp Gateway" },
      { timestamp: "18:16", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Martín Ruiz" },
      { timestamp: "18:20", fromStatus: "CONFIRMADO", toStatus: "EN_PREPARACION", user: "Cocina (Chef Laura)" },
    ],
  },
  {
    id: "PED-1018",
    customerName: "Lucía Paredes",
    customerPhone: "+54 11 8899-0011",
    channel: "web",
    type: "inmediato",
    status: "LISTO",
    items: [
      { productId: "prod-01", name: "Empanada de Carne Cortada a Cuchillo", quantity: 3, unitPrice: 5500 },
      { productId: "prod-08", name: "Agua Mineral sin Gas 500ml", quantity: 1, unitPrice: 3500 },
    ],
    total: 20000,
    createdAt: "18:05",
    estimatedMinutes: 15,
    elapsedMinutes: 18,
    urgency: "A_TIEMPO",
    turnNumber: 7,
    notes: "Retiro por mostrador.",
    history: [
      { timestamp: "18:05", toStatus: "NUEVO", user: "Portal Web" },
      { timestamp: "18:07", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Sistema" },
      { timestamp: "18:10", fromStatus: "CONFIRMADO", toStatus: "EN_PREPARACION", user: "Cocina" },
      { timestamp: "18:24", fromStatus: "EN_PREPARACION", toStatus: "LISTO", user: "Chef Carlos", note: "Comanda horneada y empaquetada lista para retiro" },
    ],
  },
  {
    id: "PED-1015",
    customerName: "Gonzalo Herrera",
    customerPhone: "+54 11 2233-4455",
    channel: "telefono",
    type: "inmediato",
    status: "FINALIZADO",
    items: [
      { productId: "prod-05", name: "Combo Docena Mixta Clásica", quantity: 1, unitPrice: 54000 },
    ],
    total: 54000,
    createdAt: "17:30",
    estimatedMinutes: 20,
    elapsedMinutes: 22,
    urgency: "A_TIEMPO",
    history: [
      { timestamp: "17:30", toStatus: "NUEVO", user: "Operador" },
      { timestamp: "17:32", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Operador" },
      { timestamp: "17:35", fromStatus: "CONFIRMADO", toStatus: "EN_PREPARACION", user: "Cocina" },
      { timestamp: "17:50", fromStatus: "EN_PREPARACION", toStatus: "LISTO", user: "Cocina" },
      { timestamp: "17:54", fromStatus: "LISTO", toStatus: "FINALIZADO", user: "Caja Mostrador", note: "Entregado a repartidor con ticket firmado." },
    ],
  },
  {
    id: "PED-1012",
    customerName: "Fabián Duarte",
    channel: "web",
    type: "inmediato",
    status: "CANCELADO",
    items: [
      { productId: "prod-04", name: "Empanada de Humita Cremosa", quantity: 6, unitPrice: 4800 },
    ],
    total: 28800,
    createdAt: "16:40",
    estimatedMinutes: 15,
    elapsedMinutes: 5,
    urgency: "A_TIEMPO",
    cancellationReason: "Insumo de humita agotado en stock antes de preparación.",
    history: [
      { timestamp: "16:40", toStatus: "NUEVO", user: "Portal Web" },
      { timestamp: "16:44", fromStatus: "NUEVO", toStatus: "CANCELADO", user: "Martín Ruiz", note: "Cancelado por falta de insumo de choclo fresco." },
    ],
  },
];

export const INITIAL_PROGRAMADOS: Pedido[] = [
  {
    id: "PRG-201",
    customerName: "Estudio Jurídico Alvear",
    customerPhone: "+54 11 4890-1122",
    customerAddress: "Av. Alvear 1450, Piso 3",
    channel: "web",
    type: "programado",
    status: "CONFIRMADO",
    items: [
      { productId: "prod-05", name: "Combo Docena Mixta Clásica", quantity: 2, unitPrice: 54000 },
      { productId: "prod-07", name: "Gaseosa Cola 354ml", quantity: 4, unitPrice: 4500 },
    ],
    total: 126000,
    createdAt: "14:00",
    scheduledDate: "Hoy",
    scheduledTime: "20:30",
    estimatedMinutes: 25,
    elapsedMinutes: 0,
    urgency: "A_TIEMPO",
    notes: "Almuerzo de directorio. Factura A requerida.",
    history: [{ timestamp: "14:00", toStatus: "CONFIRMADO", user: "Programación Web" }],
  },
  {
    id: "PRG-202",
    customerName: "Consultora Nexo (Recurrente Lunes)",
    customerPhone: "+54 11 6677-8899",
    customerAddress: "Leandro N. Alem 855",
    channel: "whatsapp",
    type: "recurrente",
    recurringFrequency: "Todos los lunes",
    status: "CONFIRMADO",
    items: [
      { productId: "prod-06", name: "Combo Ejecutivo Express", quantity: 15, unitPrice: 18500 },
    ],
    total: 277500,
    createdAt: "09:00",
    scheduledDate: "Mañana",
    scheduledTime: "13:00",
    estimatedMinutes: 45,
    elapsedMinutes: 0,
    urgency: "A_TIEMPO",
    notes: "Pedido corporativo semanal pactado.",
    history: [{ timestamp: "09:00", toStatus: "CONFIRMADO", user: "Regla Recurrencia #REC-01" }],
  },
];

export const INITIAL_AUTOMATIONS: AutomationRule[] = [
  {
    id: "AUT-01",
    name: "Confirmación Automática de Pedidos Elegibles",
    description: "Si el pedido ingresa por Web o WhatsApp, los productos están disponibles en stock y la capacidad de cocina está en nivel Óptimo o Moderado, confirmar de inmediato.",
    isActive: true,
    triggerType: "order_created",
    conditions: {
      checkProductsAvailable: true,
      checkBusinessHours: true,
      checkKitchenCapacity: true,
      channel: "todos",
    },
    actionType: "auto_confirm",
    lastExecuted: "Hace 12 min (PED-1022)",
    executionCount: 142,
  },
  {
    id: "AUT-02",
    name: "Alerta Temprana de Demora Operativa (+15 min)",
    description: "Si una comanda en preparación supera los 15 minutos sin ser marcada como lista, elevar automáticamente una incidencia de severidad Alta al supervisor.",
    isActive: true,
    triggerType: "delay_threshold",
    conditions: {
      checkProductsAvailable: false,
      checkBusinessHours: true,
      checkKitchenCapacity: false,
      maxElapsedMinutes: 15,
    },
    actionType: "raise_incidence",
    lastExecuted: "Hace 28 min (PED-1020)",
    executionCount: 18,
  },
];

export const INITIAL_RECURRENCES: RecurrenceConfig[] = [
  {
    id: "REC-01",
    customerName: "Consultora Nexo S.A.",
    companyName: "Nexo RRHH",
    phone: "+54 11 6677-8899",
    frequency: "Todos los lunes",
    scheduledTime: "13:00",
    items: [
      { productId: "prod-06", name: "Combo Ejecutivo Express", quantity: 15, unitPrice: 18500 },
    ],
    total: 277500,
    isActive: true,
    nextExecution: "Lunes 13:00",
    lastExecutionStatus: "Exitoso",
  },
  {
    id: "REC-02",
    customerName: "Agencia Creativa Zenith",
    companyName: "Zenith Media",
    phone: "+54 11 9988-7766",
    frequency: "Todos los viernes",
    scheduledTime: "20:00",
    items: [
      { productId: "prod-05", name: "Combo Docena Mixta Clásica", quantity: 4, unitPrice: 54000 },
      { productId: "prod-07", name: "Gaseosa Cola 354ml", quantity: 8, unitPrice: 4500 },
    ],
    total: 252000,
    isActive: true,
    nextExecution: "Viernes 20:00",
    lastExecutionStatus: "Exitoso",
  },
];

export const INITIAL_SHIFT_INFO: ShiftInfo = {
  name: "La Casa de las Empanadas · Sucursal Central",
  currentShift: "Turno Noche · 16:00 - 00:00",
  capacityStatus: "Moderada",
  capacityPercent: 72,
  currentActiveOrdersCount: 6,
  maxRecommendedOrders: 10,
  suggestedPrepBufferMinutes: 5,
  activeStaff: [
    { id: "st-1", name: "Carlos Rossi", role: "Cocinero principal", status: "Activo", station: "Horno", assignedOrdersCount: 3 },
    { id: "st-2", name: "Laura Menéndez", role: "Ayudante de cocina", status: "Activo", station: "Armado", assignedOrdersCount: 2 },
    { id: "st-3", name: "Lucas Gómez", role: "Cajero", status: "Activo", station: "Caja", assignedOrdersCount: 1 },
    { id: "st-4", name: "Matías Varela", role: "Repartidor", status: "Activo", station: "Empaque", assignedOrdersCount: 2 },
    { id: "st-5", name: "Martín Ruiz", role: "Supervisor", status: "Activo", station: "Horno", assignedOrdersCount: 0 },
  ],
};

export const INITIAL_INCIDENCIAS: Incidencia[] = [
  {
    id: "INC-01",
    title: "Retraso en Comanda PED-1020 (+6 min sobre pactado)",
    severity: "Alta",
    type: "pedido_retrasado",
    orderId: "PED-1020",
    timestamp: "18:31",
    description: "Comanda de 3 docenas mixtas superó los 40 min estimados por sobredemanda de horneado.",
    isResolved: false,
  },
  {
    id: "INC-02",
    title: "Insumo Humita Agotado en Catálogo",
    severity: "Media",
    type: "producto_desactivado",
    timestamp: "16:40",
    description: "Producto 'Empanada de Humita Cremosa' desactivado por quiebre de stock en cocina.",
    isResolved: true,
  },
  {
    id: "INC-03",
    title: "Revisión Manual Obligatoria: Mensaje WhatsApp con baja certeza",
    severity: "Media",
    type: "error_interpretacion",
    timestamp: "17:10",
    description: "Cliente solicitó 'lo de siempre con salsa rara'. Requiere confirmación con cajero.",
    isResolved: true,
  },
];

export const INITIAL_KPIS: ResumenKPIs = {
  pedidosHoy: 128,
  completados: 112,
  enProceso: 11,
  cancelados: 3,
  rechazados: 2,
  ingresosTotales: 3840000,
  ticketPromedio: 30000,
  tiempoPromedioPrep: 18.4,
  tasaCancelacion: 2.3,
  pedidosConIA: 54,
  eficienciaOperativa: 96.2,
};

export const INITIAL_INGREDIENTS: StockIngredientItem[] = [
  {
    id: "ing-01",
    code: "INS-CAR-01",
    name: "Carne Vacuna Especial (Nalga/Bola de Lomo)",
    category: "Carnes",
    unit: "kg",
    currentStock: 38.5,
    minThreshold: 15,
    costPerUnit: 7800,
    expiryDate: "2026-09-08",
    lotNumber: "LOT-CAR-2026-884",
    lastRestockedAt: "Ayer 14:30",
    status: "OPTIMO",
    imageUrl: "https://images.unsplash.com/photo-1588168333986-5078d3ae3976?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "ing-02",
    code: "INS-TAP-01",
    name: "Tapas de Empanadas Hojaldradas (12cm)",
    category: "Harinas y Masas",
    unit: "unid",
    currentStock: 520,
    minThreshold: 180,
    costPerUnit: 180,
    expiryDate: "2026-09-20",
    lotNumber: "LOT-TAP-990",
    lastRestockedAt: "Hace 2 días",
    status: "OPTIMO",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "ing-03",
    code: "INS-QUE-01",
    name: "Queso Mozzarella de Primera",
    category: "Lácteos",
    unit: "kg",
    currentStock: 12.0,
    minThreshold: 10,
    costPerUnit: 6900,
    expiryDate: "2026-09-12",
    lotNumber: "LOT-MOZ-441",
    lastRestockedAt: "Hace 3 días",
    status: "OPTIMO",
    imageUrl: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "ing-04",
    code: "INS-HUM-01",
    name: "Pasta de Choclo / Humita Cremosa",
    category: "Verduras",
    unit: "kg",
    currentStock: 0.5,
    minThreshold: 8.0,
    costPerUnit: 4200,
    expiryDate: "2026-09-02",
    lotNumber: "LOT-HUM-102",
    lastRestockedAt: "Hace 5 días",
    status: "CRITICO",
    imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "ing-05",
    code: "INS-BOX-01",
    name: "Cajas Térmicas para Empanadas (x12)",
    category: "Packaging",
    unit: "unid",
    currentStock: 64,
    minThreshold: 50,
    costPerUnit: 450,
    lotNumber: "BOX-OCT-01",
    lastRestockedAt: "Hoy 09:00",
    status: "OPTIMO",
    imageUrl: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "ing-06",
    code: "INS-BEB-01",
    name: "Gaseosa Cola 1.5L Línea Premium",
    category: "Bebidas",
    unit: "unid",
    currentStock: 18,
    minThreshold: 24,
    costPerUnit: 2100,
    expiryDate: "2026-12-15",
    lotNumber: "LOT-COLA-501",
    lastRestockedAt: "Ayer 11:00",
    status: "BAJO",
    imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=400&q=80",
  },
];

export const INITIAL_MOVEMENTS: StockMovement[] = [
  {
    id: "mov-01",
    ingredientId: "ing-01",
    ingredientName: "Carne Vacuna Especial (Nalga/Bola de Lomo)",
    type: "INGRESO_PROVEEDOR",
    quantity: 25.0,
    unit: "kg",
    reason: "Remito Proveedor #9042 - Frigorífico Central",
    registeredBy: "Martín Benítez",
    timestamp: "Hoy 09:15",
  },
  {
    id: "mov-02",
    ingredientId: "ing-04",
    ingredientName: "Pasta de Choclo / Humita Cremosa",
    type: "VENTA_PEDIDO",
    quantity: -3.5,
    unit: "kg",
    orderId: "PED-1020",
    reason: "Consumo automático por comanda #PED-1020",
    registeredBy: "Sistema Cocina",
    timestamp: "Hoy 12:40",
  },
  {
    id: "mov-03",
    ingredientId: "ing-03",
    ingredientName: "Queso Mozzarella de Primera",
    type: "MERMA_COCINA",
    quantity: -1.2,
    unit: "kg",
    reason: "Desecho por corte en cadena de frío de bloque abierto",
    evidenceType: "foto",
    registeredBy: "Camila Rossi",
    timestamp: "Ayer 19:30",
  },
];


// ============================================================================
// Conversaciones WhatsApp / IA — datos sembrados para el flujo Human-in-the-Loop
// Cada caso cubre un estado / motivo distinto para que el demo muestre el ciclo
// completo: IA atendiendo → requiere intervención → humano → resuelto → IA.
// ============================================================================
export const INITIAL_CONVERSATIONS: Conversation[] = [
  // 1) Conversación detallada con Comprobante de Pago Nequi / Transferencia (Requiere validación humana)
  {
    id: "CONV-01",
    customerName: "Camila Benítez",
    customerPhone: "+57 312 456-7890",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "REQUIERE_INTERVENCION",
    controlledBy: null,
    requiresHandoffReason: "VERIFICAR_PAGO_TRANSFERENCIA",
    aiConfidence: "Alta",
    orderId: "PED-1021",
    lastMessageAt: "20:16",
    unreadForOperator: true,
    messages: [
      {
        id: "m1",
        sender: "cliente",
        text: "¡Hola! Buenas noches. Quiero encargar 1 docena de empanadas surtidas para enviar a Calle 72 # 11-45 en Bogotá.",
        timestamp: "20:10",
      },
      {
        id: "m2",
        sender: "ia",
        text: "¡Hola Camila! Con gusto te ayudo. ¿Qué sabores te gustaría incluir en tu docena?\n- Carne a Cuchillo\n- Pollo al Verdeo\n- Jamón y Queso\n- Espinaca y Parmesano\n\nDocena surtida: $63.900 COP (Envío incluido).",
        timestamp: "20:11",
      },
      {
        id: "m3",
        sender: "cliente",
        text: "Por favor 6 de Carne al Horno y 6 de Pollo al Verdeo. ¿Me pasan el QR o número para pagar por Nequi o Bancolombia?",
        timestamp: "20:13",
      },
      {
        id: "m4",
        sender: "ia",
        text: "¡Excelente elección! He generado tu pre-orden #PED-1021.\n\n**Datos de Pago Oficial:**\n• **Nequi / Daviplata:** 310 987 6543\n• **Bancolombia Ahorros:** 104-892134-55\n• **Titular:** Necto Gourmet S.A.S.\n• **Total:** $63.900 COP\n\nPor favor envía la captura del comprobante aquí.",
        timestamp: "20:14",
      },
      {
        id: "m5",
        sender: "cliente",
        text: "Listo! Ya les transferí los $63.900 desde mi Nequi. Acá les adjunto la captura de pantalla con el número de aprobación.",
        timestamp: "20:16",
        attachmentUrl: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=600&q=80",
        attachmentType: "comprobante",
        attachmentMeta: {
          bank: "Nequi",
          amount: 63900,
          reference: "NQ-8941208B",
          status: "PENDIENTE_VERIFICACION",
        },
      },
      {
        id: "m6",
        sender: "ia",
        text: "He recibido tu comprobante de Nequi por $63.900 (Ref: #NQ-8941208B).\n\n*Por seguridad bancaria, un Administrador está validando la acreditación en la cuenta del restaurante para autorizar la preparación inmediata en cocina.*",
        timestamp: "20:16",
      },
    ],
    handoffHistory: [
      { timestamp: "20:16", toStatus: "REQUIERE_INTERVENCION", user: "Asistente IA", note: "Comprobante Nequi adjunto: requiere validación de fondos en app bancaria por parte de un humano." },
    ],
  },

  // 2) REQUIERE_INTERVENCION — Pedido corporativo con solicitud de factura electrónica
  {
    id: "CONV-02",
    customerName: "Tech Solutions (Federico)",
    customerPhone: "+57 301 555-4321",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "REQUIERE_INTERVENCION",
    controlledBy: null,
    requiresHandoffReason: "AMBIGUO",
    aiConfidence: "Media",
    orderId: "PED-1020",
    lastMessageAt: "18:24",
    unreadForOperator: true,
    messages: [
      { id: "m1", sender: "cliente", text: "Buenas tardes, necesitamos 8 docenas de empanadas surtidas para una reunión de directorio mañana a las 12:30 hs puntual. ¿Hacen Factura Electrónica con RUT a nombre de Tech Solutions S.A.S NIT 901.234.567-8?", timestamp: "18:20" },
      { id: "m2", sender: "ia", text: "¡Hola Federico! Sí, emitimos Factura Electrónica DIAN y preparamos pedidos corporativos programados. El total por 8 docenas (96 empanadas surtidas) es de $440.000 COP con entrega bonificada.", timestamp: "18:21" },
      { id: "m3", sender: "cliente", text: "¿Nos pueden mandar 3 docenas de Carne, 3 de Jamón y Queso, y 2 de Humita en cajas térmicas separadas? Si me confirman la factura les transfiero por Bancolombia ya.", timestamp: "18:24" },
    ],
    handoffHistory: [
      { timestamp: "18:24", toStatus: "REQUIERE_INTERVENCION", user: "Asistente IA", note: "Pedido corporativo de alto volumen: requiere validar NIT y emisión de Factura Electrónica." },
    ],
  },

  // 3) REQUIERE_INTERVENCION — Modificación de dirección en pedido en curso
  {
    id: "CONV-03",
    customerName: "Lucía Paredes",
    customerPhone: "+57 318 889-0011",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "REQUIERE_INTERVENCION",
    controlledBy: null,
    requiresHandoffReason: "CLIENTE_PIDE_HUMANO",
    aiConfidence: "Media",
    lastMessageAt: "19:08",
    unreadForOperator: true,
    messages: [
      { id: "m1", sender: "cliente", text: "Hola! Hice un pedido por la web hace 5 minutos (#PED-1025) pero me equivoqué en el número de departamento. Puse Apto 402 y es Torre 2 Apto 1402.", timestamp: "19:05" },
      { id: "m2", sender: "ia", text: "¡Hola Lucía! He ubicado tu pedido #PED-1025 en cocina. Para modificar los datos de entrega de un ticket ya confirmado, transfiero de inmediato tu solicitud al operador.", timestamp: "19:06" },
      { id: "m3", sender: "cliente", text: "Por favor que no se vaya el repartidor al bloque equivocado, estoy esperando abajo.", timestamp: "19:08" },
    ],
    handoffHistory: [
      { timestamp: "19:06", toStatus: "REQUIERE_INTERVENCION", user: "Asistente IA", note: "Cambio de dirección en comanda activa." },
    ],
  },

  // 4) IA_ATENDIENDO — Pedido rápido cerrado 100% automático por IA
  {
    id: "CONV-05",
    customerName: "Mariana Silva",
    customerPhone: "+57 315 948-1102",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "IA_ATENDIENDO",
    controlledBy: null,
    aiConfidence: "Alta",
    orderId: "PED-1024",
    lastMessageAt: "20:08",
    unreadForOperator: false,
    messages: [
      { id: "m1", sender: "cliente", text: "Hola! Quiero 6 empanadas de carne cortada a cuchillo al horno y 2 gaseosas de 500ml.", timestamp: "20:06" },
      { id: "m2", sender: "ia", text: "¡Hola Mariana! Registrado:\n- 6x Empanadas de Carne a Cuchillo ($33.000 COP)\n- 2x Coca-Cola 500ml ($8.000 COP)\n\nTotal: $41.000 COP.\nDirección registrada: Cra 15 # 85-30, Apto 301.\n¿Confirmamos con pago contra entrega en efectivo?", timestamp: "20:07" },
      { id: "m3", sender: "cliente", text: "Sí, confirmo! Pago con billete de $50.000 al recibir.", timestamp: "20:08" },
      { id: "m4", sender: "ia", text: "¡Comanda #PED-1024 confirmada y enviada a cocina! El repartidor llevará $9.000 de cambio. Tiempo estimado: 20 minutos.", timestamp: "20:08" },
    ],
    handoffHistory: [],
  },

  // 5) RESUELTO — Consulta cerrada
  {
    id: "CONV-06",
    customerName: "Ignacio Ferreyra",
    customerPhone: "+57 320 334-9988",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "RESUELTO",
    controlledBy: null,
    aiConfidence: "Alta",
    orderId: "PED-1022",
    lastMessageAt: "17:40",
    unreadForOperator: false,
    messages: [
      { id: "m1", sender: "cliente", text: "Hola, ¿tienen opción vegetariana hoy?", timestamp: "17:30" },
      { id: "m2", sender: "ia", text: "¡Hola Ignacio! Sí, disponemos de Espinaca a la Crema con Parmesano, Cuatro Quesos, y Caprese con Albahaca Fresca.", timestamp: "17:31" },
      { id: "m3", sender: "cliente", text: "Genial, paso por el local en 20 minutos a retirar una docena surtida de esas.", timestamp: "17:35" },
      { id: "m4", sender: "ia", text: "¡Te esperamos! Tu pedido para retirar en mostrador quedó listo.", timestamp: "17:36" },
    ],
    handoffHistory: [
      { timestamp: "17:40", toStatus: "RESUELTO", user: "Asistente IA", note: "Consulta completada exitosamente." },
    ],
  },
];
