import {
  Pedido,
  ProductItem,
  AutomationRule,
  RecurrenceConfig,
  ShiftInfo,
  Incidencia,
  ResumenKPIs,
  StockIngredientItem,
  StockMovement,
  Conversation,
} from "./types";
import { BusinessType, Business } from "@/context/BusinessContext";

export const RETAIL_PRODUCTS: ProductItem[] = [
  {
    id: "prod-hw-01",
    code: "FER-001",
    name: "Taladro Percutor DeWalt 650W VVR",
    category: "Herramientas Eléctricas",
    price: 280000,
    imageUrl: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 24,
    prepTimeMinutes: 15,
    description: "Motor potente de 650W con velocidad variable y reversa. Mandril de 1/2 pulgada.",
    demandTag: "Alta demanda",
    activeOrdersCount: 2,
    salesCount: 310,
    popularityRank: 1,
    rating: 4.9,
    reviewsCount: 89,
    modifiers: [
      {
        id: "mod-garantia",
        title: "Garantía Extendida",
        minSelect: 0,
        maxSelect: 1,
        options: [
          { id: "opt-g1", name: "Garantía Fábrica 1 Año (Incluida)", priceDelta: 0, isDefault: true },
          { id: "opt-g2", name: "Garantía Total 2 Años (+ Protección caídas)", priceDelta: 35000 },
        ],
      },
      {
        id: "mod-accesorios",
        title: "Accesorios para Obra",
        minSelect: 0,
        maxSelect: 2,
        options: [
          { id: "opt-acc-1", name: "Kit 5 Brocas Concreto Bosch", priceDelta: 24000 },
          { id: "opt-acc-2", name: "Guantes de Vaqueta Reforzados", priceDelta: 12000 },
        ],
      },
    ],
  },
  {
    id: "prod-hw-02",
    code: "FER-002",
    name: "Juego de Destornilladores Stanley 6 Piezas",
    category: "Herramientas Manuales",
    price: 45000,
    imageUrl: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 40,
    prepTimeMinutes: 10,
    description: "Puntas magnéticas tratadas térmicamente para máxima durabilidad en taller y hogar.",
    demandTag: "Más vendido",
    activeOrdersCount: 1,
    salesCount: 520,
    popularityRank: 2,
    rating: 4.8,
    reviewsCount: 124,
  },
  {
    id: "prod-hw-03",
    code: "FER-003",
    name: "Caja Tornillos Drywall 6x1-5/8 (1000u)",
    category: "Fijaciones & Tornillería",
    price: 32000,
    imageUrl: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 120,
    prepTimeMinutes: 5,
    description: "Tornillos fosfatados negros para placas de yeso o estructura metálica liviana.",
    demandTag: "Stock abundante",
    activeOrdersCount: 3,
    salesCount: 1450,
    popularityRank: 3,
    rating: 4.9,
    reviewsCount: 88,
  },
  {
    id: "prod-hw-04",
    code: "FER-004",
    name: "Esmalte Sintético Anticorrosivo 1 Galón Blanco",
    category: "Pinturas & Químicos",
    price: 85000,
    imageUrl: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 18,
    prepTimeMinutes: 15,
    description: "Pintura base solvente para protección de metales en intemperie y estructuras.",
    demandTag: "Lote nuevo",
    activeOrdersCount: 1,
    salesCount: 180,
    popularityRank: 4,
    rating: 4.7,
    reviewsCount: 42,
  },
  {
    id: "prod-hw-05",
    code: "FER-005",
    name: "Cinta Métrica 5m / 16ft Uso Pesado",
    category: "Medición & Trazado",
    price: 18500,
    imageUrl: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 65,
    prepTimeMinutes: 5,
    description: "Cinta de acero graduada en milímetros y pulgadas con carcasa antichoque.",
    demandTag: "Básico",
    activeOrdersCount: 1,
    salesCount: 890,
    popularityRank: 5,
    rating: 4.8,
    reviewsCount: 67,
  },
  {
    id: "prod-hw-06",
    code: "FER-006",
    name: "Disco de Corte Diamantado 4.5\"",
    category: "Abrasivos & Corte",
    price: 22000,
    imageUrl: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 50,
    prepTimeMinutes: 5,
    description: "Corte rápido y limpio en concreto, ladrillo, baldosa y mampostería.",
    demandTag: "Consumible",
    activeOrdersCount: 2,
    salesCount: 640,
    popularityRank: 6,
    rating: 4.8,
    reviewsCount: 53,
  },
];

export const FOOD_PRODUCTS: ProductItem[] = [
  {
    id: "prod-01",
    code: "EMP-01",
    name: "Empanada de Carne Cortada a Cuchillo",
    category: "Empanadas",
    price: 5500,
    imageUrl: "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 45,
    prepTimeMinutes: 12,
    description: "Carne tierna seleccionada, cebolla de verdeo, huevo duro y especias autóctonas en masa hojaldrada.",
    demandTag: "Alta demanda",
    activeOrdersCount: 4,
    salesCount: 482,
    popularityRank: 1,
    rating: 4.9,
    reviewsCount: 146,
    modifiers: [
      {
        id: "mod-coccion-1",
        title: "Tipo de Cocción",
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: "opt-c-1", name: "Al Horno de Piedra (Recomendado)", priceDelta: 0, isDefault: true },
          { id: "opt-c-2", name: "Frita en Grasa Criolla", priceDelta: 500 },
        ],
      },
      {
        id: "mod-salsa-1",
        title: "Salsa Extra Opcional",
        minSelect: 0,
        maxSelect: 2,
        options: [
          { id: "opt-s-1", name: "Chimichurri Casero 60ml", priceDelta: 1500 },
          { id: "opt-s-2", name: "Salsa Criolla Picante 60ml", priceDelta: 1500 },
        ],
      },
    ],
    reviews: [
      {
        id: "rev-1",
        author: "Santiago Morales",
        rating: 5,
        date: "Hace 2 días",
        comment: "La mejor empanada de carne de la zona. Jugosa, masa crujiente y sin exceso de grasa.",
        verifiedOrder: true,
      },
      {
        id: "rev-2",
        author: "Valeria Gómez",
        rating: 5,
        date: "Hace 4 días",
        comment: "El corte a cuchillo se nota muchísimo en la textura. Llegaron bien calientes al trabajo.",
        verifiedOrder: true,
      },
      {
        id: "rev-3",
        author: "Martín P.",
        rating: 4,
        date: "Hace 1 semana",
        comment: "Excelente sabor, muy bien condimentada. 100% recomendada.",
        verifiedOrder: true,
      },
    ],
  },
  {
    id: "prod-02",
    code: "EMP-02",
    name: "Empanada de Pollo al Verdeo",
    category: "Empanadas",
    price: 5500,
    imageUrl: "https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 32,
    prepTimeMinutes: 12,
    description: "Pechuga desmenuzada, morrón rojo salteado y salsa cremosa de verdeo.",
    demandTag: "Alta demanda",
    activeOrdersCount: 3,
    salesCount: 365,
    popularityRank: 2,
    rating: 4.8,
    reviewsCount: 98,
    modifiers: [
      {
        id: "mod-coccion-2",
        title: "Tipo de Cocción",
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: "opt-c-3", name: "Al Horno de Piedra", priceDelta: 0, isDefault: true },
          { id: "opt-c-4", name: "Frita", priceDelta: 500 },
        ],
      },
    ],
    reviews: [
      {
        id: "rev-4",
        author: "Camila R.",
        rating: 5,
        date: "Hace 3 días",
        comment: "Súper cremosa y el pollo muy tierno. Es mi favorita para pedir en la oficina.",
        verifiedOrder: true,
      },
      {
        id: "rev-5",
        author: "Nicolás B.",
        rating: 5,
        date: "Hace 6 días",
        comment: "La combinación de verdeo y pollo es perfecta. Excelente cocción en horno.",
        verifiedOrder: true,
      },
    ],
  },
  {
    id: "prod-03",
    code: "EMP-03",
    name: "Empanada de Jamón y Queso Mozzarella",
    category: "Empanadas",
    price: 5200,
    imageUrl: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 28,
    prepTimeMinutes: 10,
    description: "Jamón cocido de primera calidad y abundante queso mozzarella fundido.",
    activeOrdersCount: 2,
    salesCount: 290,
    popularityRank: 4,
    rating: 4.7,
    reviewsCount: 84,
    reviews: [
      {
        id: "rev-6",
        author: "Esteban D.",
        rating: 5,
        date: "Hace 5 días",
        comment: "Queso de verdad que estira y buen jamón. Los chicos las adoran.",
        verifiedOrder: true,
      },
    ],
  },
  {
    id: "prod-04",
    code: "EMP-04",
    name: "Empanada de Humita Cremosa",
    category: "Empanadas",
    price: 4800,
    imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: false,
    stockEstimated: 0,
    prepTimeMinutes: 10,
    description: "Choclo dulce en grano y crema suave con toque de nuez moscada y queso criollo.",
    demandTag: "Sugerencia de promo",
    activeOrdersCount: 0,
    salesCount: 180,
    popularityRank: 6,
    rating: 4.6,
    reviewsCount: 52,
    reviews: [
      {
        id: "rev-7",
        author: "Lucía Fernández",
        rating: 5,
        date: "Hace 1 semana",
        comment: "Relleno dulce en su punto exacto. Lástima que se agota rápido.",
        verifiedOrder: true,
      },
    ],
  },
  {
    id: "prod-05",
    code: "CMB-01",
    name: "Combo Docena Mixta Clásica",
    category: "Combos",
    price: 54000,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 20,
    prepTimeMinutes: 20,
    description: "12 empanadas a elección del maestro pastelero + 2 salsas caseras + 2 bebidas 500ml.",
    demandTag: "Alta demanda",
    activeOrdersCount: 5,
    salesCount: 340,
    popularityRank: 3,
    rating: 4.9,
    reviewsCount: 112,
    modifiers: [
      {
        id: "mod-beb-combo",
        title: "Elige las 2 Bebidas Incluidas",
        minSelect: 2,
        maxSelect: 2,
        options: [
          { id: "opt-b-1", name: "Gaseosa Cola 354ml", priceDelta: 0, isDefault: true },
          { id: "opt-b-2", name: "Limonada Natural", priceDelta: 1000 },
          { id: "opt-b-3", name: "Agua Mineral 500ml", priceDelta: 0 },
        ],
      },
    ],
    reviews: [
      {
        id: "rev-8",
        author: "Grupo Tech Solutions",
        rating: 5,
        date: "Ayer",
        comment: "Pedimos 3 combos para el almuerzo del equipo. Llegó todo impecable y a tiempo.",
        verifiedOrder: true,
      },
    ],
  },
  {
    id: "prod-06",
    code: "CMB-02",
    name: "Combo Ejecutivo Express",
    category: "Combos",
    price: 18500,
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 30,
    prepTimeMinutes: 10,
    description: "3 empanadas a elección + 1 gaseosa o agua mineral + 1 alfajor artesanal de postre.",
    activeOrdersCount: 2,
    salesCount: 245,
    popularityRank: 5,
    rating: 4.8,
    reviewsCount: 76,
    reviews: [
      {
        id: "rev-9",
        author: "Franco Martínez",
        rating: 5,
        date: "Hace 2 días",
        comment: "La relación precio-calidad es insuperable para el almuerzo diario.",
        verifiedOrder: true,
      },
    ],
  },
  {
    id: "prod-07",
    code: "ACOM-01",
    name: "Papas Rústicas al Romero",
    category: "Acompañamientos",
    price: 8500,
    imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 25,
    prepTimeMinutes: 15,
    description: "Papas cortadas a mano con piel, horneadas con aceite de oliva, sal marina y romero fresco.",
    demandTag: "Alta demanda",
    activeOrdersCount: 3,
    salesCount: 195,
    popularityRank: 7,
    rating: 4.9,
    reviewsCount: 42,
    modifiers: [
      {
        id: "mod-tam-papas",
        title: "Elige tu Tamaño de Porción",
        minSelect: 1,
        maxSelect: 1,
        options: [
          { id: "opt-p-reg", name: "Porción Individual (250g)", priceDelta: 0, isDefault: true },
          { id: "opt-p-gra", name: "Porción Familiar para Compartir (500g)", priceDelta: 5500 },
        ],
      },
    ],
    reviews: [],
  },
  {
    id: "prod-08",
    code: "ACOM-02",
    name: "Salsa Chimichurri Casera 120ml",
    category: "Acompañamientos",
    price: 3000,
    imageUrl: "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 50,
    prepTimeMinutes: 1,
    description: "Receta tradicional con perejil fresco, orégano, ajo y ají molido macerado.",
    activeOrdersCount: 4,
    salesCount: 310,
    popularityRank: 8,
    rating: 4.9,
    reviewsCount: 35,
    reviews: [],
  },
  {
    id: "prod-09",
    code: "BEB-01",
    name: "Gaseosa Cola 354ml",
    category: "Bebidas",
    price: 4500,
    imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 60,
    prepTimeMinutes: 2,
    description: "Lata fría lista para despacho inmediato.",
    activeOrdersCount: 6,
    salesCount: 510,
    popularityRank: 9,
    rating: 4.9,
    reviewsCount: 65,
    reviews: [],
  },
  {
    id: "prod-10",
    code: "BEB-02",
    name: "Limonada Natural con Menta y Jengibre 500ml",
    category: "Bebidas",
    price: 6500,
    imageUrl: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 35,
    prepTimeMinutes: 3,
    description: "Exprimida en el momento con limones frescos, menta y hielo frappé.",
    activeOrdersCount: 4,
    salesCount: 220,
    popularityRank: 10,
    rating: 4.8,
    reviewsCount: 48,
    reviews: [],
  },
  {
    id: "prod-11",
    code: "POS-01",
    name: "Alfajor de Maicena Artesanal con Dulce de Leche",
    category: "Postres",
    price: 4000,
    imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    isAvailable: true,
    stockEstimated: 40,
    prepTimeMinutes: 1,
    description: "Tapas suaves que se deshacen en la boca, abundante dulce de leche repostero y coco rallado.",
    activeOrdersCount: 3,
    salesCount: 280,
    popularityRank: 11,
    rating: 5.0,
    reviewsCount: 55,
    reviews: [],
  },
];

export const RETAIL_ORDERS: Pedido[] = [
  {
    id: "PED-1025",
    customerName: "Ing. Roberto Méndez",
    customerPhone: "+57 300 552-8890",
    channel: "presencial",
    type: "inmediato",
    status: "NUEVO",
    items: [
      { productId: "prod-hw-05", name: "Cinta Métrica 5m / 16ft Uso Pesado", quantity: 1, unitPrice: 18500 },
    ],
    total: 18500,
    createdAt: "18:31",
    estimatedMinutes: 10,
    elapsedMinutes: 1,
    urgency: "A_TIEMPO",
    notes: "Retiro directo en mostrador bodega.",
    history: [
      { timestamp: "18:31", toStatus: "NUEVO", user: "Caja Mostrador (Lucas)" },
    ],
  },
  {
    id: "PED-1022",
    customerName: "Ignacio Ferreyra",
    customerPhone: "+57 320 334-9988",
    customerAddress: "Calle 100 # 19-61, Edificio Sigma",
    channel: "web",
    type: "inmediato",
    status: "CONFIRMADO",
    items: [
      { productId: "prod-hw-02", name: "Juego de Destornilladores Stanley 6 Piezas", quantity: 1, unitPrice: 45000 },
      { productId: "prod-hw-05", name: "Cinta Métrica 5m / 16ft", quantity: 1, unitPrice: 18500 },
    ],
    total: 63500,
    createdAt: "18:20",
    estimatedMinutes: 30,
    elapsedMinutes: 12,
    urgency: "A_TIEMPO",
    turnNumber: 14,
    history: [
      { timestamp: "18:20", toStatus: "NUEVO", user: "Portal Web StockFlow" },
      { timestamp: "18:21", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Sistema", ruleName: "Regla Conf. Automática #1" },
    ],
  },
  {
    id: "PED-1020",
    customerName: "Tech Solutions S.A.S. (Obra Torre Norte)",
    customerPhone: "+57 301 555-4321",
    customerAddress: "Av. El Dorado # 68C-61",
    channel: "whatsapp",
    type: "inmediato",
    status: "EN_PREPARACION",
    items: [
      { productId: "prod-hw-04", name: "Esmalte Sintético Anticorrosivo 1 Galón Blanco", quantity: 3, unitPrice: 85000 },
      { productId: "prod-hw-03", name: "Caja Tornillos Drywall 6x1-5/8 (1000u)", quantity: 5, unitPrice: 32000 },
    ],
    total: 415000,
    createdAt: "18:15",
    estimatedMinutes: 25,
    elapsedMinutes: 22,
    urgency: "PROXIMO",
    turnNumber: 12,
    notes: "Factura Electrónica requerida. Despacho en furgón.",
    history: [
      { timestamp: "18:15", toStatus: "NUEVO", user: "WhatsApp Bot" },
      { timestamp: "18:16", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Operador" },
      { timestamp: "18:18", fromStatus: "CONFIRMADO", toStatus: "EN_PREPARACION", user: "Bodega Picking" },
    ],
  },
  {
    id: "PED-1024",
    customerName: "Mariana Silva",
    customerPhone: "+57 312 948-1102",
    customerAddress: "Carrera 7 # 116-50, Apto 402",
    channel: "whatsapp",
    type: "inmediato",
    status: "EN_PREPARACION",
    items: [
      { productId: "prod-hw-01", name: "Taladro Percutor DeWalt 650W", quantity: 1, unitPrice: 280000, option: "Kit 5 Brocas Bosch" },
      { productId: "prod-hw-06", name: "Disco de Corte Diamantado 4.5\"", quantity: 2, unitPrice: 22000 },
    ],
    total: 324000,
    createdAt: "18:00",
    estimatedMinutes: 20,
    elapsedMinutes: 26,
    urgency: "RETRASADO",
    turnNumber: 9,
    notes: "Empacar en caja sellada con precinto de seguridad.",
    history: [
      { timestamp: "18:00", toStatus: "NUEVO", user: "WhatsApp Bot" },
      { timestamp: "18:02", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Operador" },
      { timestamp: "18:05", fromStatus: "CONFIRMADO", toStatus: "EN_PREPARACION", user: "Bodega Central" },
    ],
  },
  {
    id: "PED-1021",
    customerName: "Carlos Méndez",
    customerPhone: "+57 310 987-6543",
    customerAddress: "Carrera 15 # 85-30, Piso 3",
    channel: "whatsapp",
    type: "inmediato",
    status: "LISTO",
    items: [
      { productId: "prod-hw-01", name: "Taladro Percutor DeWalt 650W", quantity: 1, unitPrice: 280000 },
      { productId: "prod-hw-03", name: "Caja Tornillos Drywall 6x1-5/8 (1000u)", quantity: 1, unitPrice: 32000 },
    ],
    total: 312000,
    createdAt: "17:45",
    estimatedMinutes: 20,
    elapsedMinutes: 21,
    urgency: "A_TIEMPO",
    turnNumber: 8,
    notes: "Comprobante Nequi verificado. Listo para entrega en mensajería.",
    history: [
      { timestamp: "17:45", toStatus: "NUEVO", user: "WhatsApp Bot" },
      { timestamp: "17:48", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Admin Pagos" },
      { timestamp: "17:50", fromStatus: "CONFIRMADO", toStatus: "EN_PREPARACION", user: "Bodega Picking" },
      { timestamp: "18:06", fromStatus: "EN_PREPARACION", toStatus: "LISTO", user: "Encargado Despacho" },
    ],
  },
];

export const FOOD_ORDERS: Pedido[] = [
  {
    id: "PED-1024",
    customerName: "Mariana Silva",
    customerPhone: "+54 11 9482-1102",
    customerAddress: "Av. Santa Fe 3421, 4to B",
    channel: "whatsapp",
    type: "inmediato",
    status: "NUEVO",
    items: [
      { productId: "prod-01", name: "Empanada de Carne Cortada a Cuchillo", quantity: 6, unitPrice: 5500, option: "Horneada" },
      { productId: "prod-02", name: "Empanada de Pollo al Verdeo", quantity: 6, unitPrice: 5500, option: "Horneada" },
      { productId: "prod-07", name: "Gaseosa Cola 354ml", quantity: 2, unitPrice: 4500 },
    ],
    total: 75000,
    createdAt: "18:28",
    estimatedMinutes: 20,
    elapsedMinutes: 2,
    urgency: "A_TIEMPO",
    isAIOrigin: true,
    aiRawMessage: "Hola! Queremos media docena de carne a cuchillo y media de pollo al verdeo, ambas al horno, y dos cocas frías porfa.",
    aiConfidence: "Alta",
    notes: "Tocar timbre 4B directamente.",
    history: [
      {
        timestamp: "18:28",
        toStatus: "NUEVO",
        user: "Necto IA Gateway",
        note: "Interpretado con confianza Alta desde WhatsApp. Requiere confirmación manual.",
      },
    ],
  },
  {
    id: "PED-1025",
    customerName: "Dr. Roberto Méndez",
    customerPhone: "+54 11 5521-8890",
    channel: "presencial",
    type: "inmediato",
    status: "NUEVO",
    items: [
      { productId: "prod-06", name: "Combo Ejecutivo Express", quantity: 1, unitPrice: 18500, notes: "Carne suave + Pollo + Jamón/Queso" },
    ],
    total: 18500,
    createdAt: "18:31",
    estimatedMinutes: 10,
    elapsedMinutes: 1,
    urgency: "A_TIEMPO",
    notes: "Para consumir en mostrador / llevar.",
    history: [
      {
        timestamp: "18:31",
        toStatus: "NUEVO",
        user: "Cajero 1 (Lucas Gómez)",
        note: "Ingresado por mostrador directo.",
      },
    ],
  },
  {
    id: "PED-1022",
    customerName: "Ignacio Ferreyra",
    customerPhone: "+54 11 3341-9988",
    customerAddress: "Billinghurst 1840",
    channel: "web",
    type: "inmediato",
    status: "CONFIRMADO",
    items: [
      { productId: "prod-05", name: "Combo Docena Mixta Clásica", quantity: 1, unitPrice: 54000 },
    ],
    total: 54000,
    createdAt: "18:20",
    estimatedMinutes: 25,
    elapsedMinutes: 12,
    urgency: "A_TIEMPO",
    turnNumber: 14,
    history: [
      { timestamp: "18:20", toStatus: "NUEVO", user: "Portal Web Necto" },
      { timestamp: "18:21", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Sistema", ruleName: "Regla Conf. Automática #1" },
    ],
  },
  {
    id: "PED-1020",
    customerName: "Tech Solutions S.A. (Reunión)",
    customerPhone: "+54 11 4455-6677",
    customerAddress: "Av. Corrientes 1250, Piso 8",
    channel: "whatsapp",
    type: "programado",
    status: "EN_PREPARACION",
    items: [
      { productId: "prod-05", name: "Combo Docena Mixta Clásica", quantity: 3, unitPrice: 54000 },
      { productId: "prod-07", name: "Gaseosa Cola 354ml", quantity: 6, unitPrice: 4500 },
    ],
    total: 189000,
    createdAt: "17:45",
    scheduledTime: "18:45",
    estimatedMinutes: 40,
    elapsedMinutes: 46,
    urgency: "RETRASADO",
    turnNumber: 9,
    notes: "Empaquetar por separado en cajas térmicas.",
    history: [
      { timestamp: "17:45", toStatus: "NUEVO", user: "Operador (Martín Ruiz)" },
      { timestamp: "17:50", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Martín Ruiz" },
      { timestamp: "18:05", fromStatus: "CONFIRMADO", toStatus: "EN_PREPARACION", user: "Cocina (Chef Carlos)" },
    ],
  },
  {
    id: "PED-1021",
    customerName: "Camila Benítez",
    customerPhone: "+54 11 6789-1234",
    channel: "whatsapp",
    type: "inmediato",
    status: "EN_PREPARACION",
    items: [
      { productId: "prod-01", name: "Empanada de Carne Cortada a Cuchillo", quantity: 4, unitPrice: 5500 },
      { productId: "prod-03", name: "Empanada de Jamón y Queso Mozzarella", quantity: 4, unitPrice: 5200 },
    ],
    total: 42800,
    createdAt: "18:15",
    estimatedMinutes: 20,
    elapsedMinutes: 17,
    urgency: "PROXIMO",
    turnNumber: 11,
    history: [
      { timestamp: "18:15", toStatus: "NUEVO", user: "WhatsApp Gateway" },
      { timestamp: "18:16", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Martín Ruiz" },
      { timestamp: "18:20", fromStatus: "CONFIRMADO", toStatus: "EN_PREPARACION", user: "Cocina (Chef Laura)" },
    ],
  },
  {
    id: "PED-1018",
    customerName: "Lucía Paredes",
    customerPhone: "+54 11 8899-0011",
    channel: "web",
    type: "inmediato",
    status: "LISTO",
    items: [
      { productId: "prod-01", name: "Empanada de Carne Cortada a Cuchillo", quantity: 3, unitPrice: 5500 },
      { productId: "prod-08", name: "Agua Mineral sin Gas 500ml", quantity: 1, unitPrice: 3500 },
    ],
    total: 20000,
    createdAt: "18:05",
    estimatedMinutes: 15,
    elapsedMinutes: 18,
    urgency: "A_TIEMPO",
    turnNumber: 7,
    notes: "Retiro por mostrador.",
    history: [
      { timestamp: "18:05", toStatus: "NUEVO", user: "Portal Web" },
      { timestamp: "18:07", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Sistema" },
      { timestamp: "18:10", fromStatus: "CONFIRMADO", toStatus: "EN_PREPARACION", user: "Cocina" },
      { timestamp: "18:24", fromStatus: "EN_PREPARACION", toStatus: "LISTO", user: "Chef Carlos", note: "Comanda horneada y empaquetada lista para retiro" },
    ],
  },
  {
    id: "PED-1015",
    customerName: "Gonzalo Herrera",
    customerPhone: "+54 11 2233-4455",
    channel: "telefono",
    type: "inmediato",
    status: "FINALIZADO",
    items: [
      { productId: "prod-05", name: "Combo Docena Mixta Clásica", quantity: 1, unitPrice: 54000 },
    ],
    total: 54000,
    createdAt: "17:30",
    estimatedMinutes: 20,
    elapsedMinutes: 22,
    urgency: "A_TIEMPO",
    history: [
      { timestamp: "17:30", toStatus: "NUEVO", user: "Operador" },
      { timestamp: "17:32", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Operador" },
      { timestamp: "17:35", fromStatus: "CONFIRMADO", toStatus: "EN_PREPARACION", user: "Cocina" },
      { timestamp: "17:50", fromStatus: "EN_PREPARACION", toStatus: "LISTO", user: "Cocina" },
      { timestamp: "17:54", fromStatus: "LISTO", toStatus: "FINALIZADO", user: "Caja Mostrador", note: "Entregado a repartidor con ticket firmado." },
    ],
  },
  {
    id: "PED-1012",
    customerName: "Fabián Duarte",
    channel: "web",
    type: "inmediato",
    status: "CANCELADO",
    items: [
      { productId: "prod-04", name: "Empanada de Humita Cremosa", quantity: 6, unitPrice: 4800 },
    ],
    total: 28800,
    createdAt: "16:40",
    estimatedMinutes: 15,
    elapsedMinutes: 5,
    urgency: "A_TIEMPO",
    cancellationReason: "Insumo de humita agotado en stock antes de preparación.",
    history: [
      { timestamp: "16:40", toStatus: "NUEVO", user: "Portal Web" },
      { timestamp: "16:44", fromStatus: "NUEVO", toStatus: "CANCELADO", user: "Martín Ruiz", note: "Cancelado por falta de insumo de choclo fresco." },
    ],
  },
];

export const INITIAL_HISTORIAL_ORDERS: Pedido[] = [
  {
    id: "PED-1011",
    customerName: "Laura Restrepo",
    customerPhone: "+57 311 456 7890",
    channel: "whatsapp",
    type: "inmediato",
    status: "FINALIZADO",
    paymentMethod: "transferencia",
    items: [
      { productId: "prod-05", name: "Combo Docena Mixta Clásica", quantity: 2, unitPrice: 54000 },
      { productId: "prod-07", name: "Gaseosa Cola 1.5L", quantity: 2, unitPrice: 7500 },
    ],
    total: 123000,
    createdAt: "15:10",
    estimatedMinutes: 20,
    elapsedMinutes: 22,
    urgency: "A_TIEMPO",
    isStockConsumed: true,
    history: [
      { timestamp: "15:10", toStatus: "NUEVO", user: "WhatsApp Auto" },
      { timestamp: "15:12", fromStatus: "NUEVO", toStatus: "CONFIRMADO", user: "Caja" },
      { timestamp: "15:15", fromStatus: "CONFIRMADO", toStatus: "EN_PREPARACION", user: "Cocina" },
      { timestamp: "15:30", fromStatus: "EN_PREPARACION", toStatus: "LISTO", user: "Cocina" },
      { timestamp: "15:32", fromStatus: "LISTO", toStatus: "FINALIZADO", user: "Repartidor 1", note: "Entregado a domicilio en Chicó." },
    ],
  },
  {
    id: "PED-1010",
    customerName: "Banco de Bogotá - Sucursal 80",
    customerPhone: "+57 300 987 6543",
    channel: "presencial",
    type: "inmediato",
    status: "FINALIZADO",
    paymentMethod: "pos",
    items: [
      { productId: "prod-06", name: "Combo Ejecutivo Express", quantity: 6, unitPrice: 18500 },
    ],
    total: 111000,
    createdAt: "14:40",
    estimatedMinutes: 15,
    elapsedMinutes: 14,
    urgency: "A_TIEMPO",
    isStockConsumed: true,
    history: [
      { timestamp: "14:40", toStatus: "FINALIZADO", user: "Caja Mostrador", note: "Venta directa de mostrador cobrada con Datáfono." },
    ],
  },
  {
    id: "PED-1009",
    customerName: "Camila Varela",
    customerPhone: "+57 315 222 3344",
    channel: "web",
    type: "inmediato",
    status: "FINALIZADO",
    paymentMethod: "mercadopago",
    items: [
      { productId: "prod-01", name: "Empanada de Carne Cortada a Cuchillo", quantity: 4, unitPrice: 5500 },
      { productId: "prod-02", name: "Empanada de Jamón y Muzzarella", quantity: 4, unitPrice: 5200 },
    ],
    total: 42800,
    createdAt: "14:15",
    estimatedMinutes: 20,
    elapsedMinutes: 19,
    urgency: "A_TIEMPO",
    isStockConsumed: true,
    history: [
      { timestamp: "14:15", toStatus: "FINALIZADO", user: "Repartidor 2", note: "Entregado con éxito." },
    ],
  },
  {
    id: "PED-1008",
    customerName: "Andrés Silva",
    customerPhone: "+57 318 777 8899",
    channel: "whatsapp",
    type: "inmediato",
    status: "FINALIZADO",
    paymentMethod: "transferencia",
    items: [
      { productId: "prod-01", name: "Empanada de Carne Cortada a Cuchillo", quantity: 6, unitPrice: 5500 },
      { productId: "prod-03", name: "Empanada de Pollo al Verdeo Suave", quantity: 6, unitPrice: 5200 },
    ],
    total: 64200,
    createdAt: "13:50",
    estimatedMinutes: 25,
    elapsedMinutes: 24,
    urgency: "A_TIEMPO",
    isStockConsumed: true,
    history: [
      { timestamp: "13:50", toStatus: "FINALIZADO", user: "Repartidor 1" },
    ],
  },
  {
    id: "PED-1007",
    customerName: "Oficinas WeWork Calle 100",
    customerPhone: "+57 301 555 4433",
    channel: "presencial",
    type: "inmediato",
    status: "FINALIZADO",
    paymentMethod: "transferencia",
    items: [
      { productId: "prod-05", name: "Combo Docena Mixta Clásica", quantity: 3, unitPrice: 54000 },
    ],
    total: 162000,
    createdAt: "13:20",
    estimatedMinutes: 25,
    elapsedMinutes: 22,
    urgency: "A_TIEMPO",
    isStockConsumed: true,
    history: [
      { timestamp: "13:20", toStatus: "FINALIZADO", user: "Caja Mostrador" },
    ],
  },
  {
    id: "PED-1006",
    customerName: "Santiago Gil",
    customerPhone: "+57 320 888 1122",
    channel: "telefono",
    type: "inmediato",
    status: "FINALIZADO",
    paymentMethod: "efectivo",
    items: [
      { productId: "prod-01", name: "Empanada de Carne Cortada a Cuchillo", quantity: 4, unitPrice: 5500 },
      { productId: "prod-07", name: "Gaseosa Cola 1.5L", quantity: 1, unitPrice: 7500 },
    ],
    total: 29500,
    createdAt: "12:55",
    estimatedMinutes: 15,
    elapsedMinutes: 16,
    urgency: "A_TIEMPO",
    isStockConsumed: true,
    history: [
      { timestamp: "12:55", toStatus: "FINALIZADO", user: "Caja Mostrador" },
    ],
  },
  {
    id: "PED-1005",
    customerName: "Mariana Pardo",
    customerPhone: "+57 312 333 4455",
    channel: "whatsapp",
    type: "inmediato",
    status: "FINALIZADO",
    paymentMethod: "transferencia",
    items: [
      { productId: "prod-02", name: "Empanada de Jamón y Muzzarella", quantity: 8, unitPrice: 5200 },
    ],
    total: 41600,
    createdAt: "12:30",
    estimatedMinutes: 20,
    elapsedMinutes: 18,
    urgency: "A_TIEMPO",
    isStockConsumed: true,
    history: [
      { timestamp: "12:30", toStatus: "FINALIZADO", user: "Repartidor 2" },
    ],
  },
  {
    id: "PED-1004",
    customerName: "Carlos Mario Duque",
    customerPhone: "+57 317 666 9900",
    channel: "presencial",
    type: "inmediato",
    status: "FINALIZADO",
    paymentMethod: "efectivo",
    items: [
      { productId: "prod-06", name: "Combo Ejecutivo Express", quantity: 2, unitPrice: 18500 },
    ],
    total: 37000,
    createdAt: "12:10",
    estimatedMinutes: 10,
    elapsedMinutes: 8,
    urgency: "A_TIEMPO",
    isStockConsumed: true,
    history: [
      { timestamp: "12:10", toStatus: "FINALIZADO", user: "Caja Mostrador" },
    ],
  },
  {
    id: "PED-1003",
    customerName: "Juliana Caicedo",
    customerPhone: "+57 314 999 1100",
    channel: "web",
    type: "inmediato",
    status: "FINALIZADO",
    paymentMethod: "mercadopago",
    items: [
      { productId: "prod-05", name: "Combo Docena Mixta Clásica", quantity: 1, unitPrice: 54000 },
      { productId: "prod-08", name: "Agua Mineral sin Gas 500ml", quantity: 2, unitPrice: 3500 },
    ],
    total: 61000,
    createdAt: "11:45",
    estimatedMinutes: 20,
    elapsedMinutes: 19,
    urgency: "A_TIEMPO",
    isStockConsumed: true,
    history: [
      { timestamp: "11:45", toStatus: "FINALIZADO", user: "Repartidor 1" },
    ],
  },
];

export const INITIAL_PROGRAMADOS: Pedido[] = [
  {
    id: "PRG-201",
    customerName: "Estudio Jurídico Alvear",
    customerPhone: "+54 11 4890-1122",
    customerAddress: "Av. Alvear 1450, Piso 3",
    channel: "web",
    type: "programado",
    status: "CONFIRMADO",
    items: [
      { productId: "prod-05", name: "Combo Docena Mixta Clásica", quantity: 2, unitPrice: 54000 },
      { productId: "prod-07", name: "Gaseosa Cola 354ml", quantity: 4, unitPrice: 4500 },
    ],
    total: 126000,
    createdAt: "14:00",
    scheduledDate: "Hoy",
    scheduledTime: "20:30",
    estimatedMinutes: 25,
    elapsedMinutes: 0,
    urgency: "A_TIEMPO",
    notes: "Almuerzo de directorio. Factura A requerida.",
    history: [{ timestamp: "14:00", toStatus: "CONFIRMADO", user: "Programación Web" }],
  },
  {
    id: "PRG-202",
    customerName: "Consultora Nexo (Recurrente Lunes)",
    customerPhone: "+54 11 6677-8899",
    customerAddress: "Leandro N. Alem 855",
    channel: "whatsapp",
    type: "recurrente",
    recurringFrequency: "Todos los lunes",
    status: "CONFIRMADO",
    items: [
      { productId: "prod-06", name: "Combo Ejecutivo Express", quantity: 15, unitPrice: 18500 },
    ],
    total: 277500,
    createdAt: "09:00",
    scheduledDate: "Mañana",
    scheduledTime: "13:00",
    estimatedMinutes: 45,
    elapsedMinutes: 0,
    urgency: "A_TIEMPO",
    notes: "Pedido corporativo semanal pactado.",
    history: [{ timestamp: "09:00", toStatus: "CONFIRMADO", user: "Regla Recurrencia #REC-01" }],
  },
];

export const RETAIL_PROGRAMADOS: Pedido[] = [
  {
    id: "PRG-201",
    customerName: "Constructora Conconcreto S.A.S.",
    customerPhone: "+57 301 445-8890",
    customerAddress: "Calle 100 # 19-61, Obra Torre Alpha",
    channel: "web",
    type: "programado",
    status: "CONFIRMADO",
    items: [
      { productId: "prod-hw-01", name: "Taladro Percutor DeWalt 650W", quantity: 2, unitPrice: 280000 },
      { productId: "prod-hw-03", name: "Caja Tornillos Drywall 6x1-5/8 (1000u)", quantity: 6, unitPrice: 32000 },
    ],
    total: 752000,
    createdAt: "09:30",
    scheduledDate: "Hoy",
    scheduledTime: "15:30",
    estimatedMinutes: 30,
    elapsedMinutes: 0,
    urgency: "A_TIEMPO",
    notes: "Despacho en furgón a zona de cargue de obra. Presentar remisión con firma de ingeniero residente.",
    history: [{ timestamp: "09:30", toStatus: "CONFIRMADO", user: "Portal B2B StockFlow" }],
  },
  {
    id: "PRG-202",
    customerName: "Ferretería & Acabados del Norte",
    customerPhone: "+57 312 889-4455",
    customerAddress: "Av. Boyacá # 72-10, Bodega 4",
    channel: "whatsapp",
    type: "recurrente",
    recurringFrequency: "Todos los lunes y jueves",
    status: "CONFIRMADO",
    items: [
      { productId: "prod-hw-04", name: "Esmalte Sintético Anticorrosivo 1 Galón Blanco", quantity: 8, unitPrice: 85000 },
      { productId: "prod-hw-06", name: "Disco de Corte Diamantado 4.5\"", quantity: 15, unitPrice: 22000 },
    ],
    total: 1010000,
    createdAt: "08:15",
    scheduledDate: "Mañana",
    scheduledTime: "10:00",
    estimatedMinutes: 40,
    elapsedMinutes: 0,
    urgency: "A_TIEMPO",
    notes: "Pedido mayorista recurrente. Enviar con factura electrónica impresa y certificado de calidad.",
    history: [{ timestamp: "08:15", toStatus: "CONFIRMADO", user: "Regla Recurrencia #REC-01" }],
  },
  {
    id: "PRG-203",
    customerName: "Ing. Mauricio Restrepo",
    customerPhone: "+57 300 112-9900",
    customerAddress: "Carrera 7 # 156-20, Apto 901",
    channel: "whatsapp",
    type: "programado",
    status: "CONFIRMADO",
    items: [
      { productId: "prod-hw-02", name: "Juego de Destornilladores Stanley 6 Piezas", quantity: 2, unitPrice: 45000 },
      { productId: "prod-hw-05", name: "Cinta Métrica 5m / 16ft Uso Pesado", quantity: 3, unitPrice: 18500 },
    ],
    total: 145500,
    createdAt: "11:20",
    scheduledDate: "Mañana",
    scheduledTime: "16:00",
    estimatedMinutes: 20,
    elapsedMinutes: 0,
    urgency: "A_TIEMPO",
    notes: "Entrega pactada después de las 4pm. Pago acreditado por Bancolombia.",
    history: [{ timestamp: "11:20", toStatus: "CONFIRMADO", user: "Asesor Comercial WhatsApp" }],
  },
];

export const INITIAL_AUTOMATIONS: AutomationRule[] = [
  {
    id: "AUT-01",
    name: "Confirmación Automática de Pedidos Elegibles",
    description: "Si el pedido ingresa por Web o WhatsApp, los productos están disponibles en stock y la capacidad de cocina está en nivel Óptimo o Moderado, confirmar de inmediato.",
    isActive: true,
    triggerType: "order_created",
    conditions: {
      checkProductsAvailable: true,
      checkBusinessHours: true,
      checkKitchenCapacity: true,
      channel: "todos",
    },
    actionType: "auto_confirm",
    lastExecuted: "Hace 12 min (PED-1022)",
    executionCount: 142,
  },
  {
    id: "AUT-02",
    name: "Alerta Temprana de Demora Operativa (+15 min)",
    description: "Si una comanda en preparación supera los 15 minutos sin ser marcada como lista, elevar automáticamente una incidencia de severidad Alta al supervisor.",
    isActive: true,
    triggerType: "delay_threshold",
    conditions: {
      checkProductsAvailable: false,
      checkBusinessHours: true,
      checkKitchenCapacity: false,
      maxElapsedMinutes: 15,
    },
    actionType: "raise_incidence",
    lastExecuted: "Hace 28 min (PED-1020)",
    executionCount: 18,
  },
];

export const INITIAL_RECURRENCES: RecurrenceConfig[] = [
  {
    id: "REC-01",
    customerName: "Consultora Nexo S.A.",
    companyName: "Nexo RRHH",
    phone: "+54 11 6677-8899",
    frequency: "Todos los lunes",
    scheduledTime: "13:00",
    items: [
      { productId: "prod-06", name: "Combo Ejecutivo Express", quantity: 15, unitPrice: 18500 },
    ],
    total: 277500,
    isActive: true,
    nextExecution: "Lunes 13:00",
    lastExecutionStatus: "Exitoso",
  },
  {
    id: "REC-02",
    customerName: "Agencia Creativa Zenith",
    companyName: "Zenith Media",
    phone: "+54 11 9988-7766",
    frequency: "Todos los viernes",
    scheduledTime: "20:00",
    items: [
      { productId: "prod-05", name: "Combo Docena Mixta Clásica", quantity: 4, unitPrice: 54000 },
      { productId: "prod-07", name: "Gaseosa Cola 354ml", quantity: 8, unitPrice: 4500 },
    ],
    total: 252000,
    isActive: true,
    nextExecution: "Viernes 20:00",
    lastExecutionStatus: "Exitoso",
  },
];

export const INITIAL_SHIFT_INFO: ShiftInfo = {
  name: "La Casa de las Empanadas · Sucursal Central",
  currentShift: "Turno Noche · 16:00 - 00:00",
  capacityStatus: "Moderada",
  capacityPercent: 72,
  currentActiveOrdersCount: 6,
  maxRecommendedOrders: 10,
  suggestedPrepBufferMinutes: 5,
  activeStaff: [
    { id: "st-1", name: "Carlos Rossi", role: "Cocinero principal", status: "Activo", station: "Horno", assignedOrdersCount: 3 },
    { id: "st-2", name: "Laura Menéndez", role: "Ayudante de cocina", status: "Activo", station: "Armado", assignedOrdersCount: 2 },
    { id: "st-3", name: "Lucas Gómez", role: "Cajero", status: "Activo", station: "Caja", assignedOrdersCount: 1 },
    { id: "st-4", name: "Matías Varela", role: "Repartidor", status: "Activo", station: "Empaque", assignedOrdersCount: 2 },
    { id: "st-5", name: "Martín Ruiz", role: "Supervisor", status: "Activo", station: "Horno", assignedOrdersCount: 0 },
  ],
};

export const INITIAL_INCIDENCIAS: Incidencia[] = [
  {
    id: "INC-01",
    title: "Retraso en Comanda PED-1020 (+6 min sobre pactado)",
    severity: "Alta",
    type: "pedido_retrasado",
    orderId: "PED-1020",
    timestamp: "18:31",
    description: "Comanda de 3 docenas mixtas superó los 40 min estimados por sobredemanda de horneado.",
    isResolved: false,
  },
  {
    id: "INC-02",
    title: "Insumo Humita Agotado en Catálogo",
    severity: "Media",
    type: "producto_desactivado",
    timestamp: "16:40",
    description: "Producto 'Empanada de Humita Cremosa' desactivado por quiebre de stock en cocina.",
    isResolved: true,
  },
  {
    id: "INC-03",
    title: "Revisión Manual Obligatoria: Mensaje WhatsApp con baja certeza",
    severity: "Media",
    type: "error_interpretacion",
    timestamp: "17:10",
    description: "Cliente solicitó 'lo de siempre con salsa rara'. Requiere confirmación con cajero.",
    isResolved: true,
  },
];

export const INITIAL_KPIS: ResumenKPIs = {
  pedidosHoy: 128,
  completados: 112,
  enProceso: 11,
  cancelados: 3,
  rechazados: 2,
  ingresosTotales: 3840000,
  ticketPromedio: 30000,
  tiempoPromedioPrep: 18.4,
  tasaCancelacion: 2.3,
  pedidosConIA: 54,
  eficienciaOperativa: 96.2,
};

export const INITIAL_INGREDIENTS: StockIngredientItem[] = [
  {
    id: "ing-01",
    code: "INS-CAR-01",
    name: "Carne Vacuna Especial (Nalga/Bola de Lomo)",
    category: "Carnes",
    unit: "kg",
    currentStock: 38.5,
    minThreshold: 15,
    costPerUnit: 7800,
    expiryDate: "2026-09-08",
    lotNumber: "LOT-CAR-2026-884",
    lastRestockedAt: "Ayer 14:30",
    status: "OPTIMO",
    imageUrl: "https://images.unsplash.com/photo-1588168333986-5078d3ae3976?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "ing-02",
    code: "INS-TAP-01",
    name: "Tapas de Empanadas Hojaldradas (12cm)",
    category: "Harinas y Masas",
    unit: "unid",
    currentStock: 520,
    minThreshold: 180,
    costPerUnit: 180,
    expiryDate: "2026-09-20",
    lotNumber: "LOT-TAP-990",
    lastRestockedAt: "Hace 2 días",
    status: "OPTIMO",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "ing-03",
    code: "INS-QUE-01",
    name: "Queso Mozzarella de Primera",
    category: "Lácteos",
    unit: "kg",
    currentStock: 12.0,
    minThreshold: 10,
    costPerUnit: 6900,
    expiryDate: "2026-09-12",
    lotNumber: "LOT-MOZ-441",
    lastRestockedAt: "Hace 3 días",
    status: "OPTIMO",
    imageUrl: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "ing-04",
    code: "INS-HUM-01",
    name: "Pasta de Choclo / Humita Cremosa",
    category: "Verduras",
    unit: "kg",
    currentStock: 0.5,
    minThreshold: 8.0,
    costPerUnit: 4200,
    expiryDate: "2026-09-02",
    lotNumber: "LOT-HUM-102",
    lastRestockedAt: "Hace 5 días",
    status: "CRITICO",
    imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "ing-05",
    code: "INS-BOX-01",
    name: "Cajas Térmicas para Empanadas (x12)",
    category: "Packaging",
    unit: "unid",
    currentStock: 64,
    minThreshold: 50,
    costPerUnit: 450,
    lotNumber: "BOX-OCT-01",
    lastRestockedAt: "Hoy 09:00",
    status: "OPTIMO",
    imageUrl: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "ing-06",
    code: "INS-BEB-01",
    name: "Gaseosa Cola 1.5L Línea Premium",
    category: "Bebidas",
    unit: "unid",
    currentStock: 18,
    minThreshold: 24,
    costPerUnit: 2100,
    expiryDate: "2026-12-15",
    lotNumber: "LOT-COLA-501",
    lastRestockedAt: "Ayer 11:00",
    status: "BAJO",
    imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=400&q=80",
  },
];

export const INITIAL_MOVEMENTS: StockMovement[] = [
  {
    id: "mov-01",
    ingredientId: "ing-01",
    ingredientName: "Carne Vacuna Especial (Nalga/Bola de Lomo)",
    type: "INGRESO_PROVEEDOR",
    quantity: 25.0,
    unit: "kg",
    reason: "Remito Proveedor #9042 - Frigorífico Central",
    registeredBy: "Martín Benítez",
    timestamp: "Hoy 09:15",
  },
  {
    id: "mov-02",
    ingredientId: "ing-04",
    ingredientName: "Pasta de Choclo / Humita Cremosa",
    type: "VENTA_PEDIDO",
    quantity: -3.5,
    unit: "kg",
    orderId: "PED-1020",
    reason: "Consumo automático por comanda #PED-1020",
    registeredBy: "Sistema Cocina",
    timestamp: "Hoy 12:40",
  },
  {
    id: "mov-03",
    ingredientId: "ing-03",
    ingredientName: "Queso Mozzarella de Primera",
    type: "MERMA_COCINA",
    quantity: -1.2,
    unit: "kg",
    reason: "Desecho por corte en cadena de frío de bloque abierto",
    evidenceType: "foto",
    registeredBy: "Camila Rossi",
    timestamp: "Ayer 19:30",
  },
];


// ============================================================================
// Conversaciones WhatsApp / IA — datos sembrados para el flujo Human-in-the-Loop
// Cada caso cubre un estado / motivo distinto para que el demo muestre el ciclo
// completo: IA atendiendo → requiere intervención → humano → resuelto → IA.
// ============================================================================
export const RETAIL_CONVERSATIONS: Conversation[] = [
  // 1) Comprobante de Pago Nequi por ferretería
  {
    id: "CONV-01",
    customerName: "Carlos Méndez",
    customerPhone: "+57 310 987-6543",
    avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "REQUIERE_INTERVENCION",
    controlledBy: null,
    requiresHandoffReason: "VERIFICAR_PAGO_TRANSFERENCIA",
    aiConfidence: "Alta",
    orderId: "PED-1021",
    lastMessageAt: "20:16",
    unreadForOperator: true,
    messages: [
      {
        id: "m1",
        sender: "cliente",
        text: "¡Hola! Buenas tardes. Necesito un taladro percutor de 650W y una caja de tornillos drywall de 1 pulgada para enviar a Carrera 15 # 85-30 en Bogotá.",
        timestamp: "20:10",
      },
      {
        id: "m2",
        sender: "ia",
        text: "¡Hola mi niño! Bienvenido a Ferretería La Tuerca 🔩 Con gusto te ayudo. Te confirmo la disponibilidad:\n• 1× Taladro Percutor 650W Profesional ($280.000)\n• 1× Caja Tornillos Drywall 6x1-5/8 (1000u) ($32.000)\n\nSubtotal: $312.000 COP (Envío asegurado incluido).\n¿Deseas pagar por Nequi o Bancolombia?",
        timestamp: "20:11",
      },
      {
        id: "m3",
        sender: "cliente",
        text: "Por Nequi por favor. Pásame el número para transferir ya mismo.",
        timestamp: "20:13",
      },
      {
        id: "m4",
        sender: "ia",
        text: "¡Excelente! Pre-orden generada #PED-1021.\n\n**Datos de Pago Oficial:**\n• **Nequi / Daviplata:** 310 987 6543\n• **Bancolombia Ahorros:** 104-892134-55\n• **Titular:** Ferretería La Tuerca S.A.S.\n• **Total:** $312.000 COP\n\nPor favor envía la captura del comprobante aquí.",
        timestamp: "20:14",
      },
      {
        id: "m5",
        sender: "cliente",
        text: "Listo! Ya les transferí los $312.000 desde mi Nequi. Acá les adjunto la captura de pantalla con el número de aprobación.",
        timestamp: "20:16",
        attachmentUrl: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=600&q=80",
        attachmentType: "comprobante",
        attachmentMeta: {
          bank: "Nequi",
          amount: 312000,
          reference: "NQ-8941208B",
          status: "PENDIENTE_VERIFICACION",
        },
      },
      {
        id: "m6",
        sender: "ia",
        text: "He recibido tu comprobante de Nequi por $312.000 (Ref: #NQ-8941208B).\n\n*Por seguridad bancaria, un Administrador está validando la acreditación en cuenta bancaria para autorizar el embalaje y despacho inmediato en bodega.*",
        timestamp: "20:16",
      },
    ],
    handoffHistory: [
      { timestamp: "20:16", toStatus: "REQUIERE_INTERVENCION", user: "Asistente IA", note: "Comprobante Nequi adjunto: requiere validación de fondos en app bancaria por parte de un humano." },
    ],
  },
  {
    id: "CONV-02",
    customerName: "Tech Solutions (Federico)",
    customerPhone: "+57 301 555-4321",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "REQUIERE_INTERVENCION",
    controlledBy: null,
    requiresHandoffReason: "AMBIGUO",
    aiConfidence: "Media",
    orderId: "PED-1020",
    lastMessageAt: "18:24",
    unreadForOperator: true,
    messages: [
      { id: "m1", sender: "cliente", text: "Buenas tardes, necesitamos 3 galones de esmalte blanco anticorrosivo y 5 cajas de tornillos drywall para obra mañana a primera hora. ¿Emiten Factura Electrónica a Tech Solutions S.A.S NIT 901.234.567-8?", timestamp: "18:20" },
      { id: "m2", sender: "ia", text: "¡Hola Federico! Sí, emitimos Factura Electrónica DIAN y coordinamos despachos de materiales pesados. El total por los 3 galones y 5 cajas de tornillos es de $415.000 COP con flete bonificado.", timestamp: "18:21" },
      { id: "m3", sender: "cliente", text: "Perfecto. Si me confirman la factura con el NIT les transfiero ya mismo por Bancolombia.", timestamp: "18:24" },
    ],
    handoffHistory: [
      { timestamp: "18:24", toStatus: "REQUIERE_INTERVENCION", user: "Asistente IA", note: "Pedido corporativo de obra: requiere validar NIT y emisión de Factura Electrónica." },
    ],
  },
  {
    id: "CONV-03",
    customerName: "Lucía Paredes",
    customerPhone: "+57 318 889-0011",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "REQUIERE_INTERVENCION",
    controlledBy: null,
    requiresHandoffReason: "CLIENTE_PIDE_HUMANO",
    aiConfidence: "Media",
    lastMessageAt: "19:08",
    unreadForOperator: true,
    messages: [
      { id: "m1", sender: "cliente", text: "Hola! Hice un pedido por la web hace 10 minutos (#PED-1022) pero me equivoqué de dirección de entrega. Puse Calle 100 # 19-61 y es Carrera 19 # 100-21 Oficina 402.", timestamp: "19:05" },
      { id: "m2", sender: "ia", text: "¡Hola Lucía! He ubicado tu pedido #PED-1022 en bodega. Para modificar los datos de entrega de una orden en preparación, transfiero de inmediato tu solicitud al operador.", timestamp: "19:06" },
      { id: "m3", sender: "cliente", text: "Por favor que no despachen al transportador a la dirección vieja, gracias!", timestamp: "19:08" },
    ],
    handoffHistory: [
      { timestamp: "19:06", toStatus: "REQUIERE_INTERVENCION", user: "Asistente IA", note: "Cambio de dirección en despacho activo." },
    ],
  },
  {
    id: "CONV-05",
    customerName: "Mariana Silva",
    customerPhone: "+57 312 948-1102",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "IA_ATENDIENDO",
    controlledBy: null,
    aiConfidence: "Alta",
    orderId: "PED-1024",
    lastMessageAt: "18:28",
    unreadForOperator: false,
    messages: [
      { id: "m1", sender: "cliente", text: "Hola! Tienen disponible un taladro percutor de 650W y discos de corte diamantado?", timestamp: "18:26" },
      { id: "m2", sender: "ia", text: "¡Hola Mariana! Sí, contamos con stock inmediato:\n• 1× Taladro Percutor DeWalt 650W — $280.000\n• 2× Disco de Corte Diamantado 4.5\" — $44.000\n\nTotal: $324.000 COP\nDirección registrada: Carrera 7 # 116-50, Apto 402\n¿Deseas confirmar la orden para empaque y despacho inmediato?", timestamp: "18:27" },
      { id: "m3", sender: "cliente", text: "Sí, confirmo! Empáquenlo bien por favor.", timestamp: "18:28" },
      { id: "m4", sender: "ia", text: "¡Perfecto! Hemos generado tu orden #PED-1024 y ya está en cola de bodega para picking y embalaje. Tiempo estimado: 25 min.", timestamp: "18:28" },
    ],
    handoffHistory: [],
  },
  {
    id: "CONV-06",
    customerName: "Ignacio Ferreyra",
    customerPhone: "+57 320 334-9988",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "RESUELTO",
    controlledBy: null,
    aiConfidence: "Alta",
    orderId: "PED-1022",
    lastMessageAt: "17:40",
    unreadForOperator: false,
    messages: [
      { id: "m1", sender: "cliente", text: "Hola, ¿el juego de destornilladores Stanley tiene garantía de por vida?", timestamp: "17:30" },
      { id: "m2", sender: "ia", text: "¡Hola Ignacio! Sí, la línea profesional Stanley cuenta con garantía directa de fábrica contra defectos de manufactura.", timestamp: "17:31" },
      { id: "m3", sender: "cliente", text: "Excelente, ya lo compro por la web para retirar en punto físico.", timestamp: "17:35" },
      { id: "m4", sender: "ia", text: "¡Te esperamos! Tu orden quedará lista para retiro en mostrador.", timestamp: "17:36" },
    ],
    handoffHistory: [
      { timestamp: "17:40", toStatus: "RESUELTO", user: "Asistente IA", note: "Consulta técnica completada." },
    ],
  },
];

export const FOOD_CONVERSATIONS: Conversation[] = [
  // 1) Conversación detallada con Comprobante de Pago Nequi / Transferencia (Requiere validación humana)
  {
    id: "CONV-01",
    customerName: "Camila Benítez",
    customerPhone: "+57 312 456-7890",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "REQUIERE_INTERVENCION",
    controlledBy: null,
    requiresHandoffReason: "VERIFICAR_PAGO_TRANSFERENCIA",
    aiConfidence: "Alta",
    orderId: "PED-1021",
    lastMessageAt: "20:16",
    unreadForOperator: true,
    messages: [
      {
        id: "m1",
        sender: "cliente",
        text: "¡Hola! Buenas noches. Quiero encargar 1 docena de empanadas surtidas para enviar a Calle 72 # 11-45 en Bogotá.",
        timestamp: "20:10",
      },
      {
        id: "m2",
        sender: "ia",
        text: "¡Hola Camila! Con gusto te ayudo. ¿Qué sabores te gustaría incluir en tu docena?\n- Carne a Cuchillo\n- Pollo al Verdeo\n- Jamón y Queso\n- Espinaca y Parmesano\n\nDocena surtida: $63.900 COP (Envío incluido).",
        timestamp: "20:11",
      },
      {
        id: "m3",
        sender: "cliente",
        text: "Por favor 6 de Carne al Horno y 6 de Pollo al Verdeo. ¿Me pasan el QR o número para pagar por Nequi o Bancolombia?",
        timestamp: "20:13",
      },
      {
        id: "m4",
        sender: "ia",
        text: "¡Excelente elección! He generado tu pre-orden #PED-1021.\n\n**Datos de Pago Oficial:**\n• **Nequi / Daviplata:** 310 987 6543\n• **Bancolombia Ahorros:** 104-892134-55\n• **Titular:** Necto Gourmet S.A.S.\n• **Total:** $63.900 COP\n\nPor favor envía la captura del comprobante aquí.",
        timestamp: "20:14",
      },
      {
        id: "m5",
        sender: "cliente",
        text: "Listo! Ya les transferí los $63.900 desde mi Nequi. Acá les adjunto la captura de pantalla con el número de aprobación.",
        timestamp: "20:16",
        attachmentUrl: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=600&q=80",
        attachmentType: "comprobante",
        attachmentMeta: {
          bank: "Nequi",
          amount: 63900,
          reference: "NQ-8941208B",
          status: "PENDIENTE_VERIFICACION",
        },
      },
      {
        id: "m6",
        sender: "ia",
        text: "He recibido tu comprobante de Nequi por $63.900 (Ref: #NQ-8941208B).\n\n*Por seguridad bancaria, un Administrador está validando la acreditación en la cuenta del restaurante para autorizar la preparación inmediata en cocina.*",
        timestamp: "20:16",
      },
    ],
    handoffHistory: [
      { timestamp: "20:16", toStatus: "REQUIERE_INTERVENCION", user: "Asistente IA", note: "Comprobante Nequi adjunto: requiere validación de fondos en app bancaria por parte de un humano." },
    ],
  },

  // 2) REQUIERE_INTERVENCION — Pedido corporativo con solicitud de factura electrónica
  {
    id: "CONV-02",
    customerName: "Tech Solutions (Federico)",
    customerPhone: "+57 301 555-4321",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "REQUIERE_INTERVENCION",
    controlledBy: null,
    requiresHandoffReason: "AMBIGUO",
    aiConfidence: "Media",
    orderId: "PED-1020",
    lastMessageAt: "18:24",
    unreadForOperator: true,
    messages: [
      { id: "m1", sender: "cliente", text: "Buenas tardes, necesitamos 8 docenas de empanadas surtidas para una reunión de directorio mañana a las 12:30 hs puntual. ¿Hacen Factura Electrónica con RUT a nombre de Tech Solutions S.A.S NIT 901.234.567-8?", timestamp: "18:20" },
      { id: "m2", sender: "ia", text: "¡Hola Federico! Sí, emitimos Factura Electrónica DIAN y preparamos pedidos corporativos programados. El total por 8 docenas (96 empanadas surtidas) es de $440.000 COP con entrega bonificada.", timestamp: "18:21" },
      { id: "m3", sender: "cliente", text: "¿Nos pueden mandar 3 docenas de Carne, 3 de Jamón y Queso, y 2 de Humita en cajas térmicas separadas? Si me confirman la factura les transfiero por Bancolombia ya.", timestamp: "18:24" },
    ],
    handoffHistory: [
      { timestamp: "18:24", toStatus: "REQUIERE_INTERVENCION", user: "Asistente IA", note: "Pedido corporativo de alto volumen: requiere validar NIT y emisión de Factura Electrónica." },
    ],
  },

  // 3) REQUIERE_INTERVENCION — Modificación de dirección en pedido en curso
  {
    id: "CONV-03",
    customerName: "Lucía Paredes",
    customerPhone: "+57 318 889-0011",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "REQUIERE_INTERVENCION",
    controlledBy: null,
    requiresHandoffReason: "CLIENTE_PIDE_HUMANO",
    aiConfidence: "Media",
    lastMessageAt: "19:08",
    unreadForOperator: true,
    messages: [
      { id: "m1", sender: "cliente", text: "Hola! Hice un pedido por la web hace 5 minutos (#PED-1025) pero me equivoqué en el número de departamento. Puse Apto 402 y es Torre 2 Apto 1402.", timestamp: "19:05" },
      { id: "m2", sender: "ia", text: "¡Hola Lucía! He ubicado tu pedido #PED-1025 en cocina. Para modificar los datos de entrega de un ticket ya confirmado, transfiero de inmediato tu solicitud al operador.", timestamp: "19:06" },
      { id: "m3", sender: "cliente", text: "Por favor que no se vaya el repartidor al bloque equivocado, estoy esperando abajo.", timestamp: "19:08" },
    ],
    handoffHistory: [
      { timestamp: "19:06", toStatus: "REQUIERE_INTERVENCION", user: "Asistente IA", note: "Cambio de dirección en comanda activa." },
    ],
  },

  // 4) IA_ATENDIENDO — Pedido rápido cerrado 100% automático por IA (Mariana Silva PED-1024)
  {
    id: "CONV-05",
    customerName: "Mariana Silva",
    customerPhone: "+54 11 9482-1102",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "IA_ATENDIENDO",
    controlledBy: null,
    aiConfidence: "Alta",
    orderId: "PED-1024",
    lastMessageAt: "18:28",
    unreadForOperator: false,
    messages: [
      {
        id: "m1",
        sender: "cliente",
        text: "Hola! Queremos media docena de carne a cuchillo y media de pollo al verdeo, ambas al horno, y dos cocas frías porfa.",
        timestamp: "18:26",
      },
      {
        id: "m2",
        sender: "ia",
        text: "¡Hola Mariana! Qué delicia de pedido. Te confirmo la comanda:\n• 6× Empanadas de Carne a Cuchillo (Horneadas) — $33.000\n• 6× Empanadas de Pollo al Verdeo (Horneadas) — $33.000\n• 2× Gaseosa Cola 354ml Frías — $9.000\n\nTotal: $75.000 COP\nDirección registrada: Av. Santa Fe 3421, 4to B\n\n¿Deseas confirmar la orden para mandarla a cocina de inmediato?",
        timestamp: "18:27",
      },
      {
        id: "m3",
        sender: "cliente",
        text: "Sí, confirmo! Tocar timbre 4B directamente.",
        timestamp: "18:28",
      },
      {
        id: "m4",
        sender: "ia",
        text: "¡Perfecto! Hemos generado tu comanda #PED-1024 y ya está en cola de cocina para confirmación y horneado. Tiempo estimado: 20 min.",
        timestamp: "18:28",
      },
    ],
    handoffHistory: [],
  },

  // 5) RESUELTO — Consulta cerrada
  {
    id: "CONV-06",
    customerName: "Ignacio Ferreyra",
    customerPhone: "+57 320 334-9988",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    channel: "whatsapp",
    status: "RESUELTO",
    controlledBy: null,
    aiConfidence: "Alta",
    orderId: "PED-1022",
    lastMessageAt: "17:40",
    unreadForOperator: false,
    messages: [
      { id: "m1", sender: "cliente", text: "Hola, ¿tienen opción vegetariana hoy?", timestamp: "17:30" },
      { id: "m2", sender: "ia", text: "¡Hola Ignacio! Sí, disponemos de Espinaca a la Crema con Parmesano, Cuatro Quesos, y Caprese con Albahaca Fresca.", timestamp: "17:31" },
      { id: "m3", sender: "cliente", text: "Genial, paso por el local en 20 minutos a retirar una docena surtida de esas.", timestamp: "17:35" },
      { id: "m4", sender: "ia", text: "¡Te esperamos! Tu pedido para retirar en mostrador quedó listo.", timestamp: "17:36" },
    ],
    handoffHistory: [
      { timestamp: "17:40", toStatus: "RESUELTO", user: "Asistente IA", note: "Consulta completada exitosamente." },
    ],
  },
];

// ============================================================================
// Factory Helpers per Business Archetype
// Permite que el sistema adapte catálogo, órdenes en vivo e hilos de WhatsApp
// dinámicamente según el negocio activo seleccionado (Ferretería, Restaurante, etc.)
// ============================================================================
export function getMockProductsForBusiness(businessType?: BusinessType, _businessName?: string): ProductItem[] {
  if (businessType === "restaurant_virtual" || businessType === "food_restaurant" || businessType === "food_store") {
    return FOOD_PRODUCTS;
  }
  return RETAIL_PRODUCTS;
}

export function getMockOrdersForBusiness(businessType?: BusinessType, _businessName?: string): Pedido[] {
  if (businessType === "restaurant_virtual" || businessType === "food_restaurant" || businessType === "food_store") {
    return FOOD_ORDERS;
  }
  return RETAIL_ORDERS;
}

export function getMockConversationsForBusiness(business?: Business | null): Conversation[] {
  const type = business?.businessType || "retail_store";
  if (type === "restaurant_virtual" || type === "food_restaurant" || type === "food_store") {
    return FOOD_CONVERSATIONS;
  }
  return RETAIL_CONVERSATIONS;
}

export function getMockProgramadosForBusiness(businessType?: BusinessType): Pedido[] {
  if (businessType === "restaurant_virtual" || businessType === "food_restaurant" || businessType === "food_store") {
    return INITIAL_PROGRAMADOS;
  }
  return RETAIL_PROGRAMADOS;
}

export const INITIAL_PRODUCTS: ProductItem[] = RETAIL_PRODUCTS;
export const INITIAL_ORDERS: Pedido[] = RETAIL_ORDERS;
export const INITIAL_CONVERSATIONS: Conversation[] = RETAIL_CONVERSATIONS;


