import type { BusinessType, BusinessSemanticConfig } from "./types";

export function getBusinessSemantics(businessType?: BusinessType): BusinessSemanticConfig {
  switch (businessType) {
    case "fashion_footwear":
      return {
        orderSingle: "Pedido de Calzado / Moda",
        orderPlural: "Pedidos",
        orderNoun: "Pedido",
        orderNounPlural: "Pedidos",
        stationName: "Mesa de empaque y despacho",
        stationShortName: "Empaque y envíos",
        stationNoun: "Estación de empaque y despacho",
        stationAction: "Preparar calzado para envío",
        preparationVerb: "En empaque y alistamiento",
        readyVerb: "Listo para Envío",
        deliveredVerb: "Entregados / Despachados",
        catalogItem: "Calzado / Prenda",
        tableOrChannel: "Canal de Venta",
        itemModifiers: "Talla, color y material",
        fulfillmentAgent: "Asesor de Empaque",
        requiresKitchenDisplay: false,
        requiresTableNumber: false,
        botGreetingTemplate: "¡Hola! Bienvenido a {storeName}. ¿Qué estilo o talla de calzado estás buscando hoy?",
        botPersona: "asesor de calzado y moda atento a tallas, estilos y disponibilidad",
      };
    case "hardware_store":
      return {
        orderSingle: "Pedido Ferretero",
        orderPlural: "Pedidos",
        orderNoun: "Pedido",
        orderNounPlural: "Pedidos",
        stationName: "Bodega de picking y despacho",
        stationShortName: "Bodega y despacho",
        stationNoun: "Estación de picking y despacho",
        stationAction: "Alistar materiales",
        preparationVerb: "En picking de bodega",
        readyVerb: "Listo para entrega",
        deliveredVerb: "Despachados / Facturados",
        catalogItem: "Herramienta / Material",
        tableOrChannel: "Canal de Venta",
        itemModifiers: "Medida, calibre y marca",
        fulfillmentAgent: "Bodeguero / Despachador",
        requiresKitchenDisplay: false,
        requiresTableNumber: false,
        botGreetingTemplate: "¡Hola! Bienvenido a {storeName}. ¿Qué herramienta o material necesitas para tu obra?",
        botPersona: "asesor técnico ferretero conocedor de especificaciones, medidas y herramientas",
      };
    case "pharmacy_health":
      return {
        orderSingle: "Orden Médica / Pedido",
        orderPlural: "Pedidos",
        orderNoun: "Pedido",
        orderNounPlural: "Pedidos",
        stationName: "Dispensario y despacho express",
        stationShortName: "Dispensario y envío",
        stationNoun: "Estación de Dispensario",
        stationAction: "Dispensar Medicamentos",
        preparationVerb: "En dispensación y empaque",
        readyVerb: "Listo para Domicilio",
        deliveredVerb: "Entregados a Paciente",
        catalogItem: "Medicamento / Producto",
        tableOrChannel: "Canal de Atención",
        itemModifiers: "Presentación y laboratorio",
        fulfillmentAgent: "Regente de Farmacia",
        requiresKitchenDisplay: false,
        requiresTableNumber: false,
        botGreetingTemplate: "¡Hola! Bienvenido a {storeName}. ¿En qué medicamento o producto de cuidado personal podemos ayudarte hoy?",
        botPersona: "asistente farmacéutico atento, confiable y rápido en despacho de fórmulas",
      };
    case "tech_electronics":
      return {
        orderSingle: "Orden Tecnológica",
        orderPlural: "Pedidos",
        orderNoun: "Pedido",
        orderNounPlural: "Pedidos",
        stationName: "Control de calidad y despacho",
        stationShortName: "Alistamiento técnico",
        stationNoun: "Estación de Alistamiento técnico",
        stationAction: "Verificar y empacar",
        preparationVerb: "En control y empaque",
        readyVerb: "Listo para Envío",
        deliveredVerb: "Despachados / Garantizados",
        catalogItem: "Dispositivo / Componente",
        tableOrChannel: "Canal de Venta",
        itemModifiers: "Capacidad, color y garantía",
        fulfillmentAgent: "Técnico de despacho",
        requiresKitchenDisplay: false,
        requiresTableNumber: false,
        botGreetingTemplate: "¡Hola! Bienvenido a {storeName}. ¿Qué dispositivo, repuesto o accesorio estás buscando?",
        botPersona: "asesor tecnológico enfocado en compatibilidad, garantías y especificaciones",
      };
    case "retail_store":
    case "ecommerce_direct":
      return {
        orderSingle: "Pedido de Venta",
        orderPlural: "Pedidos",
        orderNoun: "Pedido",
        orderNounPlural: "Pedidos",
        stationName: "Picking, empaque y despacho",
        stationShortName: "Picking y despacho",
        stationNoun: "Estación de picking y despacho",
        stationAction: "Preparar para Envío",
        preparationVerb: "En picking y preparación",
        readyVerb: "Listo para despacho",
        deliveredVerb: "Despachados / Entregados",
        catalogItem: "Producto / SKU",
        tableOrChannel: "Canal de Venta",
        itemModifiers: "Variantes (Talla, Color)",
        fulfillmentAgent: "Bodeguero / Despachador",
        requiresKitchenDisplay: false,
        requiresTableNumber: false,
        botGreetingTemplate: "¡Hola! Bienvenido a {storeName}. ¿Qué producto necesitas hoy?",
        botPersona: "asesor de ventas y despacho servicial y experto en catálogo de productos",
      };
    case "cafe_bakery":
      return {
        orderSingle: "Orden de Cafetería",
        orderPlural: "Órdenes",
        orderNoun: "Orden",
        orderNounPlural: "Órdenes",
        stationName: "Barra de café y horno",
        stationShortName: "Barra y café",
        stationNoun: "Barra de despacho",
        stationAction: "Preparar bebidas y panes",
        preparationVerb: "En barra y calentado",
        readyVerb: "Listo en Barra",
        deliveredVerb: "Entregado al cliente",
        catalogItem: "Bebida / Horneado",
        tableOrChannel: "Mesa / Barra / Para Llevar",
        itemModifiers: "Tipo de leche y adiciones",
        fulfillmentAgent: "Barista / Panadero",
        requiresKitchenDisplay: true,
        requiresTableNumber: true,
        botGreetingTemplate: "¡Hola! Bienvenido a {storeName}. ¿Te provoca un buen café o algo de panadería?",
        botPersona: "barista apasionado, amable y conocedor de recetas y notas de café",
      };
    case "fast_food":
      return {
        orderSingle: "Comanda Express",
        orderPlural: "Comandas",
        orderNoun: "Comanda",
        orderNounPlural: "Comandas",
        stationName: "Línea de armado y freidoras",
        stationShortName: "Cocina rápida",
        stationNoun: "Línea de Armado",
        stationAction: "Armar y despachar",
        preparationVerb: "En plancha y freidora",
        readyVerb: "Listo para Empaque",
        deliveredVerb: "Despachado / Enviado",
        catalogItem: "Combo / Entrada",
        tableOrChannel: "Mesa / Mostrador / Domicilio",
        itemModifiers: "Salsas y acompañamientos",
        fulfillmentAgent: "Cocinero express",
        requiresKitchenDisplay: true,
        requiresTableNumber: false,
        botGreetingTemplate: "¡Hola! Bienvenido a {storeName}. ¿Qué combo te preparamos hoy?",
        botPersona: "ágil, entusiasta, enfocado en promociones y tiempos de entrega rápidos",
      };
    case "bar_brewery":
      return {
        orderSingle: "Ticket de Barra",
        orderPlural: "Tickets",
        orderNoun: "Ticket",
        orderNounPlural: "Tickets",
        stationName: "Barra y grifos de cerveza",
        stationShortName: "Barra principal",
        stationNoun: "Estación de Coctelería",
        stationAction: "Servir tragos y pintas",
        preparationVerb: "En coctelera y servido",
        readyVerb: "Listo en Barra",
        deliveredVerb: "Servido en Mesa",
        catalogItem: "Trago / Cerveza",
        tableOrChannel: "Mesa / Barra",
        itemModifiers: "Hielo, mezclador y marca",
        fulfillmentAgent: "Bartender",
        requiresKitchenDisplay: true,
        requiresTableNumber: true,
        botGreetingTemplate: "¡Hola! Bienvenido a {storeName}. ¿Qué pinta o cóctel te servimos hoy?",
        botPersona: "bartender conocedor de cócteles de autor y cervezas artesanales",
      };
    case "technical_service":
      return {
        orderSingle: "Orden de Servicio",
        orderPlural: "Órdenes de Trabajo",
        orderNoun: "Orden Técnica",
        orderNounPlural: "Órdenes Técnicas",
        stationName: "Banco de diagnóstico y trabajo",
        stationShortName: "Mesa Técnica",
        stationNoun: "Banco de Trabajo Técnico",
        stationAction: "Reparar y probar",
        preparationVerb: "En Reparación / Mantenimiento",
        readyVerb: "Reparación Finalizada",
        deliveredVerb: "Entregado a Propietario",
        catalogItem: "Servicio / Repuesto",
        tableOrChannel: "Canal de Recepción",
        itemModifiers: "Falla reportada y repuestos",
        fulfillmentAgent: "Técnico Especialista",
        requiresKitchenDisplay: false,
        requiresTableNumber: false,
        botGreetingTemplate: "¡Hola! Bienvenido al centro de servicio de {storeName}. ¿Qué equipo o vehículo deseas revisar?",
        botPersona: "técnico especializado, analítico, enfocado en diagnósticos claros y presupuestos",
      };
    case "consulting_appointments":
      return {
        orderSingle: "Sesión / Asesoría",
        orderPlural: "Sesiones Agendadas",
        orderNoun: "Sesión",
        orderNounPlural: "Sesiones",
        stationName: "Sala de sesiones y consultoría",
        stationShortName: "Sala de Consultoría",
        stationNoun: "Agenda de Sesiones",
        stationAction: "Iniciar Sesión",
        preparationVerb: "Sesión en Curso",
        readyVerb: "Confirmada / Esperando Hora",
        deliveredVerb: "Sesión Completada",
        catalogItem: "Asesoría / Consultoría",
        tableOrChannel: "Canal Virtual / Presencial",
        itemModifiers: "Modalidad y temática",
        fulfillmentAgent: "Consultor / Asesor",
        requiresKitchenDisplay: false,
        requiresTableNumber: false,
        botGreetingTemplate: "¡Hola! Bienvenido a {storeName}. ¿En qué área o fecha deseas programar tu asesoría?",
        botPersona: "consultor profesional, puntual, formal y orientado a objetivos",
      };
    case "nutrition_supplements":
      return {
        orderSingle: "Pedido Nutricional",
        orderPlural: "Pedidos",
        orderNoun: "Pedido",
        orderNounPlural: "Pedidos",
        stationName: "Bodega de suplementos y empaque",
        stationShortName: "Despacho Fitness",
        stationNoun: "Estación de Picking Fitness",
        stationAction: "Alistar Suplementos",
        preparationVerb: "En Alistamiento",
        readyVerb: "Listo para Envío",
        deliveredVerb: "Entregados",
        catalogItem: "Suplemento / Proteína",
        tableOrChannel: "Canal de Venta",
        itemModifiers: "Sabor, peso y marca",
        fulfillmentAgent: "Asesor Fitness",
        requiresKitchenDisplay: false,
        requiresTableNumber: false,
        botGreetingTemplate: "¡Hola! Bienvenido a {storeName}. ¿Cuál es tu meta deportiva para asesorarte con los mejores suplementos?",
        botPersona: "asesor nutricional y fitness motivador, conocedor de suplementación y objetivos",
      };
    case "clinic_optics":
      return {
        orderSingle: "Valoración / Orden Clínica",
        orderPlural: "Órdenes Clínicas",
        orderNoun: "Orden Clínica",
        orderNounPlural: "Órdenes Clínicas",
        stationName: "Consultorio y laboratorio óptico",
        stationShortName: "Consultorio",
        stationNoun: "Consultorio de Valoración",
        stationAction: "Realizar Valoración",
        preparationVerb: "En Fabricación / Consulta",
        readyVerb: "Listo para entrega",
        deliveredVerb: "Entregado a Paciente",
        catalogItem: "Consulta / Montura",
        tableOrChannel: "Consultorio / Mostrador",
        itemModifiers: "Fórmula y tratamiento de lente",
        fulfillmentAgent: "Optómetra / Especialista",
        requiresKitchenDisplay: false,
        requiresTableNumber: false,
        botGreetingTemplate: "¡Hola! Bienvenido a {storeName}. ¿Deseas agendar tu valoración visual o cotizar lentes y monturas?",
        botPersona: "asistente clínico empático, cuidadoso de la salud visual y la puntualidad",
      };
    case "services":
      return {
        orderSingle: "Cita / Servicio",
        orderPlural: "Citas y turnos",
        orderNoun: "Cita",
        orderNounPlural: "Citas",
        stationName: "Cuadrante de Atención",
        stationShortName: "Atención y turnos",
        stationNoun: "Cuadrante de atención y citas",
        stationAction: "Iniciar Atención",
        preparationVerb: "En Atención",
        readyVerb: "Listo para Atención",
        deliveredVerb: "Atendidos / Finalizados",
        catalogItem: "Servicio / Tratamiento",
        tableOrChannel: "Box / Cabina / Puesto",
        itemModifiers: "Detalles / Duración",
        fulfillmentAgent: "Especialista / Profesional",
        requiresKitchenDisplay: false,
        requiresTableNumber: false,
        botGreetingTemplate: "¡Hola! Bienvenido a {storeName}. ¿Qué servicio deseas agendar hoy?",
        botPersona: "recepcionista y gestor de turnos cordial y organizado",
      };
    case "restaurant_virtual":
    default:
      return {
        orderSingle: "Comanda / Pedido",
        orderPlural: "Comandas",
        orderNoun: "Comanda",
        orderNounPlural: "Comandas",
        stationName: "Cocina y despacho (KDS)",
        stationShortName: "KDS Cocina",
        stationNoun: "KDS cocina y estaciones",
        stationAction: "Iniciar Preparación",
        preparationVerb: "En Cocina / Preparación",
        readyVerb: "Listo para Servir",
        deliveredVerb: "Entregados / Servidos",
        catalogItem: "Plato / Menú",
        tableOrChannel: "Mesa / Salón / Canal",
        itemModifiers: "Modificadores / Salsas",
        fulfillmentAgent: "Cocinero / Chef",
        requiresKitchenDisplay: true,
        requiresTableNumber: true,
        botGreetingTemplate: "¡Hola! Bienvenido a {storeName}. ¿Qué menú te preparamos hoy?",
        botPersona: "anfitrión gastronómico entusiasta y atento a términos de cocción y salsas",
      };
  }
}

