/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Auth@UserPool": {
      id: string;
      type: "sst.aws.CognitoUserPool";
    };
    "Auth@Client": {
      id: string;
      type: "sst.aws.CognitoUserPoolClient";
    };
    "Inventarios@Table": {
      name: string;
      type: "sst.aws.Dynamo";
    };
    "Inventarios@Api": {
      type: "sst.aws.ApiGatewayV2";
      url: string;
    };
    "Pedidos@Table": {
      name: string;
      type: "sst.aws.Dynamo";
    };
    "Pedidos@Api": {
      type: "sst.aws.ApiGatewayV2";
      url: string;
    };
  }
}

import "sst";
export {};